### ISSUE TITLE
error while executing telega command

### ISSUE THREAD

**Issue by mrazavi64** [zevlg/telega.el#1]
When I execute the telega command the following message will be shown:

    let: Symbol’s function definition is void: telega--root-genbuffer

Is the source code incomplete?

**Comment by zevlg** [comment]
Yeap, just started project

**Comment by mrazavi64** [comment]
Keep up the great work then.

**Comment by zevlg** [comment]
@mrazavi64 you could try `M-x telega RET` with last commit, not yet usable, but should not raise errors

**Comment by mrazavi64** [comment]
Nice! Now, after putting telega-server in the exec-path, 'M-x telega' asked my phone number, telegram sent me a login code, but it ended up with the following error message:

```
cond: cl-ecase failed: authorizationStateWaitPassword, (authorizationStateWaitTdlibParameters authorizationStateWaitEncryptionKey authorizationStateWaitPhoneNumber authorizationStateWaitCode authorizationStateReady authorizationStateLoggingOut authorizationStateClosing authorizationStateClosed)
```

And my buffer is like this:

```
Status: Auth WaitPassword

[0:All                       ]   [0:Secrets                   ]
[0:Users                     ]   [0:Channels                  ]
[0:Groups                    ]   [0:Bots                      ]

-----------------------------------(all)------------------------------------
```

Maybe that's because I've enabled two factor  authentication.

**Comment by zevlg** [comment]
@mrazavi64 added password based two-factor auth in e0cc4f43cd

**Comment by mrazavi64** [comment]
It was fast, dude!
I can confirm that I was able to use `telega` command to login with two-factor auth and view the list of chats I have, without any error.
Thank you :smiley:

**Comment by zevlg** [comment]
You can practice filtering chats for now, press `/ ctrl-h` in root buffer for help

**Comment by mrazavi64** [comment]
Great! I liked the default key bindings. Although `/ u` didn't work for me, everything else worked fine.
