### ISSUE TITLE
Archived chats support

### ISSUE THREAD

**Issue by 4DA** [zevlg/telega.el#100]
Very cool feature that I miss in telega

**Comment by 4DA** [comment]
Should be possible to implement after 1.6 of tdlib:
https://github.com/tdlib/td/issues/554

**Comment by zevlg** [comment]
Archived chats are not yet supported by TDLib 1.5.0 (see https://github.com/tdlib/td/issues/554)

As a workaround, you can use custom chat label in conjunction with custom chat order.  So all your "archived" chats are listed at the bottom of chat list and has custom label "Archived", so you can filter them with `/ l Archived RET` in root buffer.

Here is the command to put chat to archive:
```elisp
(defun my-telega-chat-archive (chat)
  (interactive (list (or telega-chatbuf--chat
                         (telega-chat-at-point))))
  (telega-chat-custom-order chat "1")
  (telega-chat-custom-label chat "Archived"))
```
