### ISSUE TITLE
Server install error

### ISSUE THREAD

**Issue by bepolymathe** [zevlg/telega.el#104]
With spacemacs, i have this error message 
```

make -C server install
make[1] : on entre dans le répertoire « /home/manu/.emacs.d/elpa/develop/telega-20191122.1005/server »
cc -I/usr/local/include -Wall -g -pthread -o telega-server telega-server.c telega-dat.c telega-pngext.c -L/usr/local/lib -ltdjson
telega-server.c:10:10: erreur fatale: td/telegram/td_json_client.h : Aucun fichier ou dossier de ce type
   10 | #include <td/telegram/td_json_client.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminée.
make[1]: *** [Makefile:30: telega-server] Error 1
make[1] : on quitte le répertoire « /home/manu/.emacs.d/elpa/develop/telega-20191122.1005/server »
make: *** [Makefile:6: install] Error 2
```
Any idea ?

**Comment by zevlg** [comment]
Install https://github.com/tdlib/td first as described in README.md

**Comment by bepolymathe** [comment]
I have it already install. There is a package for tdlib under fedora... but same message. Maybe a path problem ?

**Comment by zevlg** [comment]
You need dev package with headers, telega-server looks in /usr/local/include for tdlib headers

**Comment by GeorgeBekh** [comment]
Same problem here.
`sudo make install` doesn't copy any headers to `/usr/local/include`

**Comment by GeorgeBekh** [comment]
@bepolymathe you probably have to build TDLib again with *all* required deps installed. I didn't have openssl installed and TDLib gave me only a waning but didn't install properly

**Comment by brettgilio** [comment]
@bepolymathe What is the state of this issue for you?

**Comment by bepolymathe** [comment]
@brettgilio I've given up for now.

**Comment by brettgilio** [comment]
> @brettgilio I've given up for now.

I am going to close this issue for now. If the issue persists for you in the future and you decide to come back to it, we can re-open the issue. Thanks.

**Comment by benjujo** [comment]
Hello,
I have the same issue on Feodra 30.
I have installed TDLib from [here](https://github.com/tdlib/td) but it only creates a `libtdutils.a` on `/usr/local/lib`. Every dependency is on that file? Doing a `locate td_json_file` on my disk gives:
```sh
/home/my-user/td/td/telegram/td_json_client.cpp
/home/my-user/td/td/telegram/td_json_client.h
```
Should have add that path to compile telega-server?

**Comment by zevlg** [comment]
Make sure you are installed all the dev packages listed in TDLib deps. Seems like you forgot libssl-dev

See https://t.me/emacs_telega/11483

**Comment by benjujo** [comment]
On fedora, installing `tdlib-devel`it solved. But now it throw several errors(?) like
```sh
...
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libtdjson.so: referencia a `td::td_api::passportElementTypePassport::passportElementTypePassport()' sin definir
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libtdjson.so: referencia a `td::td_api::createCall::createCall()' sin definir
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libtdjson.so: referencia a `td::td_api::setBackground::setBackground()' sin definir
collect2: error: ld devolvió el estado de salida 1
make[1]: *** [Makefile:32: telega-server] Error 1
make[1]: se sale del directorio '/home/myuser/.emacs.d/elpa/telega-0.5.4/server'
make: *** [Makefile:6: install] Error 2
```
I think that this is a fedora issue

**Comment by zevlg** [comment]
Fedora is known to have broken TDLib package, see https://t.me/emacs_telega/11390

Build TDLib from sources

**Comment by benjujo** [comment]
So i installed TDLib from sources but in `/usr`, and now it's working!
