### ISSUE TITLE
Status: telega-server: exited abnormally with code 126

### ISSUE THREAD

**Issue by 404cn** [zevlg/telega.el#109]
I bulid td and install telega from melpa and i run M-x telega in emacs it says

> Installed `telega-server` version 0.0.0 [unknown] < 0.5.0, rebulid, and i type y and n

but it shows

```
Status: telega-server: exited abnormally with code 126

emacs: /home/liubo/.telega/telega-server: Exec format error
```

archlinux, kernel 5.3.13-arch1-1, emacs 26.3

**Comment by zevlg** [comment]
What does these shell commands outputs?:
```console
$ ~/.telega/telega-server -h
```
and
```console
$ file ~/.telega/telega-server
```

**Comment by 404cn** [comment]
@zevlg 

```zsh: exec format error: .telega/telega-server```

and

```.telega/telega-server: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>```

**Comment by zevlg** [comment]
Looks like corrupted binary for some reason, maybe building by hand may help, see the value for `telega--lib-directory`, then:
```console
$ cd <telega--lib-directory>
$ make clean && make install
```

**Comment by 404cn** [comment]
I delete telega folder from my elpa dir and restart emacs recompile, and it works.

@zevlg  Thanks, your reply is so quickly.
