### ISSUE TITLE
telega-chat-title: empty title

### ISSUE THREAD

**Issue by akaWolf** [zevlg/telega.el#118]
assert when title is empty in telega-chat-title

**Comment by zevlg** [comment]
Please provide more info

**Comment by akaWolf** [comment]
well the chat type is private

**Comment by zevlg** [comment]
Please read
* https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
* https://shapeshed.com/the-importance-of-a-good-bug-report/

Good practices is to provide next info, along with bug description:
1) Environment: versions, custom setup, etc
2) Steps to reproduce
3) Expected Result
4) Actual Result
5) Visual Proof: screenshots, backtraces, logs

**Comment by zevlg** [comment]
I'm closing this @akaWolf, feel free to reopen with more info provided, thanks!
