### ISSUE TITLE
telega is getting slow 

### ISSUE THREAD

**Issue by a13** [zevlg/telega.el#119]
```
telega v0.5.1 (TDLib version 1.5.1)
```

```
Network Statistics
------------------
Since: Mon

File: None via Ethernet sent: 3.7M received 8.9M
File: Thumbnail via Ethernet sent: 1.2k received 119.3k
File: ProfilePhoto via Ethernet sent: 69k received 1.1M
File: Photo via Ethernet sent: 1.9M received 30.8M
File: Video via Ethernet sent: 18.0k received 10.5M
File: Document via Ethernet sent: 1.6k received 967.2k
File: Sticker via Ethernet sent: 10.9k received 4.2M
File: Animation via Ethernet sent: 622 received 338.4k

Total sent: 5.6M
Total recv: 57.0M
```
![image](https://user-images.githubusercontent.com/251267/71018357-002f3880-2101-11ea-85b3-940f9299aafc.png)

**Comment by mrkiko** [comment]
Hi! Does this apply even with Emacs 27, 28 or any later version/branch?

**Comment by zevlg** [comment]
Could you please remove some custom filters from `telega-filters-custom` to make it smaller in length and try again, does things become faster?

**Comment by zevlg** [comment]
@a13 could you please check the latest master.  I've added delayed redisplay for the filters ewoc, so it marks as dirty and redisplays only when Emacs goes idle.

**Comment by zevlg** [comment]
Notes for @zevlg in Russian: Ещё можно за каждой кнопкой кастомных фильтров держать список чатов и нужных чисел (число непрочитаных и меншонов), которые матчатся.  Когда приходит какой-нибудь chat update event, то не пересчитывать всё полоностью для всех кастомных фильтров, а смотреть на изменение принадлежности чата к списку и вычитывать/прибавлять соответствующие числа

**Comment by zevlg** [comment]
@a13 do you still experince slow behaviour using telega from master?  Recently there was major changes how root buffer updates to implement rootview functionality

Could you please recheck this issue

Thanks
