### ISSUE TITLE
Emacs27 sticker error

### ISSUE THREAD

**Issue by toure00** [zevlg/telega.el#120]
Emacs27  default is not supported  Imagemagick, But it can display image do not show sticker,
```
(setq telega-use-images t)
```
This parameter controls the display of images and stickers
Then the images can be displayed, stickers will Error
![image](https://user-images.githubusercontent.com/33457469/71371475-3d596600-25ec-11ea-9359-0bb8418c0bda.png)

Is it possible to add a parameter specifically for controlling the display of stickers?

**Comment by zevlg** [comment]
@toure00 please check it works for you, thanks

**Comment by toure00** [comment]
This can work properly
