### ISSUE TITLE
Feature request: internal link to specifc message

### ISSUE THREAD

**Issue by nico202** [zevlg/telega.el#139]
In org-mode, it's possible to link to specific e-mail messages by using their unique id.  An implementation for notmuch (an emacs mail client) is available [here](https://gist.github.com/fedxa/fac592424473f1b70ea489cc64e08911).

It would be nice to have something similar for telegram: a link that leads to the exact message in a chat.  This is not the same as public telegram link (like those shown with `i` on a message, like: Link: https://t.me/CHATID/MESSAGEID) as it should be possible to link to any message (like saved ones).

something like:

tg:CHATID:MESSAGEID maybe

Thanks, Nicolò

**Comment by zevlg** [comment]
To implement linking in org-mode, use something like:
```elisp
(defun org-telega-follow-link (link)
  (telega-tme-open-tg (concat "tg:telega:" link)))

(defun org-telega-store-link ()
  (when-let ((link (telega-tme-internal-link-to
                    (or (telega-msg-at (point))
                        (telega-chat-at (point))))))
    ;; NOTE: strip leading "tg:"
    (let ((org-link (substring link 3)))
      (org-link-store-props :type "telega" :link org-link)
      org-link)))

(defun org-telega-complete-link ()
  (let ((chat (telega-completing-read-chat "Chat: ")))
    (concat "telega:" (number-to-string (plist-get chat :id)))))

(org-link-set-parameters "telega"
                         :follow 'org-telega-follow-link
                         :store 'org-telega-store-link
                         :complete 'org-telega-complete-link)
```

**Comment by zevlg** [comment]
You can link to given chat or to message.  In general internal link has next form:
```
tg:telega:<CHAT-ID>[#<MSG-ID>]
```
`<MSG-ID>` prefixed with `#` is optional.

In org-mode internal "tg:" prefix is not used, so it will look like `telega:<CHAT-ID>[#<MSG-ID>]` in org docs, almost identical as you proposed.

**Comment by nico202** [comment]
Wonderful, thanks!
