### ISSUE TITLE
Handling gaps in chat history

### ISSUE THREAD

**Issue by zevlg** [zevlg/telega.el#141]
According to https://github.com/tdlib/td/issues/896 chat history might have gaps.  Need to handle this properly in telega.el

However this is hard to test thing.  Need to collect update events when gap is reported, so this behaviour can be simulated for testing purposes

**Comment by levlam** [comment]
@zevlg You can change in https://github.com/tdlib/td/blob/92c9149e30318ac83baeb194ba9fcacf2bea3588/td/telegram/MessagesManager.h#L1425 the constant to 1 and rebuild TDLib. After that 2-5 messages sent to a supergroup/channel and not received while connected should be enough to create a gap. So you should be easily test on a public chat in which the user is not a member.
