### ISSUE TITLE
Wrong sort order of the pinned chats

### ISSUE THREAD

**Issue by akaWolf** [zevlg/telega.el#147]
## Operating System / Distribution
Arch Linux

## GNU Emacs Details
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

## TDLib/Telega Installation Method
Telega from MELPA
TDLib from AUR

## Current Behavior
I expect to see custom sort order of the pinned chats (the same as in the official clients).
But currently there is a broken sort order of the pinned chats.

## Possible Solution
Use field Order.

## Steps to Reproduce
Launch Telega
Try to move pinned chats in official client.
It's not moving in Telega.

**Comment by zevlg** [comment]
Thanks.  Fixed, please check it works for you
