### ISSUE TITLE
load full chat history

### ISSUE THREAD

**Issue by divansantana** [zevlg/telega.el#151]
Hey,

Thanks for this great package.

Is there a way to load the full chat history?

I know about telega-chatbuf-history-beginning which takes the chat to the beginning. But I'd like to load the full chat history so I can use something like occur through it.

**Comment by zevlg** [comment]
This is not possible.  You can load part of the history by scrolling backward and you can increase `telega-chat-history-limit`, but loading full chat history at ounce is impossible.

Searching inside chat is one of the TODO things described in https://github.com/zevlg/telega.el/blob/master/doc/ROADMAP.org#searching-messages-in-chat

**Comment by brettgilio** [comment]
Closing.
