### ISSUE TITLE
Emacs crashes when starting Telega for the first time in a while

### ISSUE THREAD

**Issue by evan3334** [zevlg/telega.el#153]
## Telega Setup
*OS*: Linux xenon 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*Emacs*: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13)
*Telega*: telega v0.6.0 (TDLib version 1.6.0)

Telega installed from GNU Guix

## Current Behavior
When starting Telega for the first time in a while, the root buffer displays the "updating" message for a short time, and then Emacs crashes. Subsequent attempts to start Telega work with no issues, until a sufficient amount of time has gone without using Telega. I don't know how much time this is, but the last time I opened Telega was about a week ago.

## Steps to Reproduce

This is going to be kind of convoluted to reproduce, sorry...

1. Allow a significant amount of time to pass without using Telega (seems to be about a week for me)
2. Start Telega with `M-x telega RET`
3. Telega will display "updating" message and then Emacs will crash shortly after.

Apologies if I missed something in this report.

**Comment by evan3334** [comment]
I have some more information on this bug:

I was just now able to get it to happen by killing the Telega root buffer and then running `M-x telega RET` again. Emacs crashed immediately. Not sure where I can get a log or anything in order to provide more information on the problem. Please let me know if there's any other info I can provide.

**Comment by zevlg** [comment]
This is definitely the Emacs bug, best you can do is to report it with <kbd>M-x report-emacs-bug RET</kbd>

To collect debug info, use gdb:
```
If Emacs crashed, and you have the Emacs process in the gdb debugger,
please include the output from the following gdb commands:
    'bt full' and 'xbacktrace'.
For information about debugging Emacs, please read the file
/usr/local/share/emacs/28.0.50/etc/DEBUG
```

**Comment by brettgilio** [comment]
Closing. Reopen if still persistent.
