### ISSUE TITLE
Doom-emacs : error in process filter: Invalid function: telega-svg-create

### ISSUE THREAD

**Issue by mdphoto** [zevlg/telega.el#155]
HI,
I install with MELPA an doom-emacs
I've this msg after M-x telega
error in process filter: Invalid function: telega-svg-create

Status: Connecting.           Fetching chats...
[0:📑Main            ]  [0:Groups            ]  [0:Channels          ]  
[0:Contacts          ]  [0:Important         ]  [0:📑Archive         ]  
-/-----------------------------------(main)-------------------------------------
Thank for help

**Comment by mdphoto** [comment]
Hi,
Sorry i forget 
(use-package telega
  :load-path  "~/telega.el"
  :commands (telega)
  :defer t)

Thank you

**Comment by zevlg** [comment]
We have got a discussion on this, see thread starting from https://t.me/emacs_telega/14117

I do not use doom myself, but there are experienced doom users in the telegram group
