### ISSUE TITLE
Ability to "save" files received/sent over Telegram

### ISSUE THREAD

**Issue by mrkiko** [zevlg/telega.el#157]
It would benice to have the ability to "save" files received in Telegram.
It would be nice if we could entirely bypass the cache mechanism, writing files directly to the place we would like to store them!

Thank you very very much for great work.

**Comment by zevlg** [comment]
It happened, this functionality already implemented in telega, press <kbd>S</kbd> while point is on the message you want to save

**Comment by mrkiko** [comment]
Not supported by TDLib.
