### ISSUE TITLE
New config snippet: side-by-side setup

### ISSUE THREAD

**Issue by mojoman** [zevlg/telega.el#163]
# Side-by-side window layout
Change widths to your liking and display resolution. This way if you split
your frame onto two windows (with rootbuf on the left and some chatbuf on the
right), chatbufs will always open on the same window, just like official
desktop client works. Also the rootbuf will try to keep itself narrow.

``` elisp
(setq telega-inserter-for-chat-button 'telega-ins--chat-full-2lines)
(setq telega-chat-button-width 15)
(setq telega-root-fill-column (+ 20 telega-chat-button-width))
(put (get 'telega-chat 'button-category-symbol)
    :inserter 'telega-ins--chat-full-2lines)
(setq switch-to-buffer-preserve-window-point t)
(setq telega-chat--display-buffer-action
    '((display-buffer-reuse-window display-buffer-use-some-window)))

```

**Comment by zevlg** [comment]
Added into https://github.com/zevlg/telega.el/wiki/Configuration-snippets#side-by-side-window-layout-by-mojoman
