### ISSUE TITLE
How to return to the original message position after jumping.

### ISSUE THREAD

**Issue by BlindingDark** [zevlg/telega.el#170]
## Telega Setup
*OS*: 5.6.10-3-MANJARO x86_64
*Emacs*: 26.3 (x86_64-pc-linux-gnu)
*Telega*: telega v0.6.12 (TDLib version 1.6.4)
*MELPA*: 20200511.1744

## Current Behavior
Can't go back to the original message after jumping to the reply message.
Is this feature included in the #103 plan, or are there other ways I haven't noticed?

**Comment by zevlg** [comment]
No way yet, yeah it is #103 for this feature
