### ISSUE TITLE
Can not get my own message

### ISSUE THREAD

**Issue by vunhan** [zevlg/telega.el#173]
## Telega Setup
*OS*:  Mac OS X 10.14.6
*Emacs*: 27.0.91 (x86_64-apple-darwin18.7.0)
*Telega*: telega v0.6.12 (TDLib version 1.6.4)

## Current Behavior

When I just start telega, instead of getting messages normally, I got these errors (debug mode was on)
Debug log: https://pastebin.com/WTnGEUKW

**Comment by zevlg** [comment]
Please check this commit is fixing the issue

**Comment by vunhan** [comment]
Thank you, this issue can be closed.
