### ISSUE TITLE
<process telega-server> -> "abort trap: 6"

### ISSUE THREAD

**Issue by shwangdev** [zevlg/telega.el#174]
## Telega Setup
*OS*: unknown
*Emacs*: 26.3 (x86_64-apple-darwin18.2.0)
*Telega*: telega v0.6.20 (TDLib version 1.6.0)

## Current Behavior

Debug log shows : <process telega-server> -> "abort trap: 6"
I can not login to telega

## Steps to Reproduce
1. telega-debug log:

>  Fri May 22 15:57:37 2020 ---[ telega-server started
> 1590134257: Status: (Disconnected . ) --> (telega-server: starting. . )
> 1590134258: event IN: (:@type "updateOption" :name "version" :value (:@type "optionValueString" :value "1.6.0"))
> 1590134258: event IN: (:@type "updateAuthorizationState" :authorization_state (:@type "authorizationStateWaitTdlibParameters"))
> 1590134258: Status: (telega-server: starting. . ) --> (Auth WaitTdlibParameters . )
> 1590134258: OUTPUT: send 493 (:@type "setTdlibParameters" :parameters (:@type "tdlibParameters" :use_test_dc :false :database_directory "/Users/shawn.wang/.telega" :files_directory "/Users/shawn.wang/.telega/cache" :use_file_database t :use_chat_info_database t :use_message_database t :use_secret_chats t :api_id 72239 :api_hash "bbf972f94cc6f0ee5da969d8d42a6c76" :system_language_code "en" :device_model "Emacs" :system_version "26.3" :application_version "0.6.20" :enable_storage_optimizer t :ignore_file_names :false))
> 1590134258: event IN: (:@type "updateAuthorizationState" :authorization_state (:@type "authorizationStateWaitEncryptionKey" :is_encrypted nil))
> 1590134258: Status: (Auth WaitTdlibParameters . ) --> (Auth WaitEncryptionKey . )
> 1590134258: OUTPUT: send 56 (:@type "checkDatabaseEncryptionKey" :encryption_key "")
> 1590134258: OUTPUT: send 135 (:@type "addProxy" :server "xxxxx" :port 1088 :enable : t :type (:@type "proxyTypeSocks5" :username "admin" :password "xxxxx"))
> 1590134258: event IN: (:@type "ok")
> 1590134258: SENTINEL: #<process telega-server> -> "abort trap: 6"

**Comment by zevlg** [comment]
Could you please attach last lines in the `~/.telega/telega-server.log` file just after crash, it shows assertion causing abortion

Thanks

**Comment by shwangdev** [comment]
@zevlg  here are last few lines of server log below.

> [ 3][t 4][1590134258.882197142][Td.cpp:3592][#1][!Td][&td_requests]	Receive request 1: setTdlibParameters {
>   parameters = tdlibParameters {
>     use_test_dc = false
>     database_directory = "/Users/shawn.wang/.telega"
>     files_directory = "/Users/shawn.wang/.telega/cache"
>     use_file_database = true
>     use_chat_info_database = true
>     use_message_database = true
>     use_secret_chats = true
>     api_id = 72239
>     api_hash = "bbf972f94cc6f0ee5da969d8d42a6c76"
>     system_language_code = "en"
>     device_model = "Emacs"
>     system_version = "26.3"
>     application_version = "0.6.20"
>     enable_storage_optimizer = true
>     ignore_file_names = false
>   }
> }
> [ 3][t 4][1590134258.882514954][Td.cpp:4707][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
>   authorization_state = authorizationStateWaitEncryptionKey {
>     is_encrypted = false
>   }
> }
> [ 3][t 4][1590134258.882539034][Td.cpp:4722][#1][!Td][&td_requests]	Sending result for request 1: ok {
> }
> [ 3][t 0][1590134258.882564306][Client.cpp:276][&td_requests]	End to wait for updates, returning object 0 0x7faac9d05cf0
> [telega-server] OUTPUT event: {"@type":"updateAuthorizationState","authorization_state":{"@type":"authorizationStateWaitEncryptionKey","is_encrypted":false}}
> [ 3][t 0][1590134258.882596254][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 0.500000
> [ 3][t 0][1590134258.882604122][Client.cpp:276][&td_requests]	End to wait for updates, returning object 1 0x7faac9d05d20
> [telega-server] OUTPUT event: {"@type":"ok"}
> [ 3][t 0][1590134258.882621050][Client.cpp:270][&td_requests]	Begin to wait for updates with timeout 0.500000
> [telega-server] INPUT: {"@type":"checkDatabaseEncryptionKey","encryption_key":""}
> Invalid plist object at pos=65
> Assertion failed: (false), function tdat_plist_object, file telega-dat.c, line 357.

**Comment by zevlg** [comment]
Looks like incorrect setup for the proxies, could you please show your setup for `telega-proxies`.  **WARN**: it could contain sensitive information, please use random strings instead of real addresses/passwords/etc

**Comment by zevlg** [comment]
Yeah, you have fantom ":" just after `:enable`

**Comment by shwangdev** [comment]
@zevlg  Good shoot... Problem resolved. Thanks in advacne.
