### ISSUE TITLE
telega-chutbuf-attach-clipboard image compressing

### ISSUE THREAD

**Issue by chernyshof** [zevlg/telega.el#176]
When I'm using telega-chutbuf-attach-clipboard image quality is low, but when I'm pasting clipboard in telegram it's all great 

## Current Behavior
Pasting images telega-chutbuf-attach-clipboard make images compressed(low quality)

## Steps to Reproduce
1. Copy image to clipboard
2. Paste it with telega-chutbuf-attach-clipboard
3. Paste it with telegram official dekstop client

## Telega Setup
*OS*: arch linux
*Emacs*: 26.3 (x86_64-pc-linux-gnu)
*Telega*: telega v0.6.22 (TDLib v1.6.0) (telega-server v0.6.3)
*MELPA*: 20200522.1943

**Comment by zevlg** [comment]
telega might **not** use highest res photo to display photo it in chatbuf.  To get highest res photo, press `RET` on photo message

Size and quality of the photo used in chatbuf is controlled by `telega-photo-maxsize`, telega will select suitable photo to be used in chatbuf according to this var

**Comment by chernyshof** [comment]
I'm not talking about viewing images in telega
I'm talking about viewing them in official clients
Images are clearly different.

**Comment by zevlg** [comment]
If you did not satistfied with how screenshots are taken, you can write your own screenshot taking function, which will take screenshot with quality you need, and then customize `telega-screenshot-function` value.

For screenshot taking functions examples, see `telega-screenshot-with-import`, `telega-screenshot-with-flameshot`,`telega-screenshot-with-gnome-screenshot`,`telega-screenshot-with-pngpaste`

**Comment by chernyshof** [comment]
I'm using the same screenshot tool for both cases(the same clipboard state)

**Comment by zevlg** [comment]
Could you please provide examples, so we can see the difference.  Paste clipboards (from telega and official client) to https://t.me/emacs_telega group

**Comment by chernyshof** [comment]
Sent

**Comment by chernyshof** [comment]
Apparently telegram donwsize screenshot for some reason
Thanks for helping
