### ISSUE TITLE
telega-url-shorten-mode in root buffer: big icon

### ISSUE THREAD

**Issue by TvoroG** [zevlg/telega.el#177]
Hey! Thanks for fantastic telegram client.

Icon of a url is too big in root buffer

[https://i.imgur.com/NOfGquk.png](https://i.imgur.com/NOfGquk.png)

## Telega Setup
*OS*: Linux user 5.4.35 #1-NixOS SMP Thu Apr 23 08:36:46 UTC 2020 x86_64 GNU/Linu
*Emacs*: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.17)
*Telega*:  telega v0.5.4 (TDLib version 1.6.0)

nixpkgs

## Steps to Reproduce

1. enable telega-url-shorten-mode
2. open telega root buffer
3. there should be a message which telega-url-shorten-mode can recognize to short it

**Comment by zevlg** [comment]
Yeah, this is Emacs 26 limitation, it can't scale svg images.

There is no workarounds (yet?) for this

**Comment by zevlg** [comment]
Set `telega-url-shorten-use-images` to nil to avoid using svg images

**Comment by zevlg** [comment]
I close this.  The only decent solution for Emacs26 is to unset `:svg-icon` property for corresponding shorten url spec
