### ISSUE TITLE
Telega occasionally requests over the undo-limit when initially fetching messages.

### ISSUE THREAD

**Issue by digitables** [zevlg/telega.el#180]
## Telega Setup
*OS*: Linux 5.7.3-arch1-1 #1 SMP PREEMPT Wed, 17 Jun 2020 19:42:12 +0000 x86_64 GNU/Linux
*Emacs*: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19
*Telega*: telega v0.6.22 (TDLib v1.6.6) (telega-server v0.6.3)

TdLib installed from AUR and from source.
Telega installed from MELPA.

## Current Behavior
When launching `M-x telega`, telega-root begins fetching messages. Eventually, the following warning emerges:
```
Warning (undo): Buffer ‘*Telega Root*’ undo info was 3251016 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.

This is normal if you executed a command that made a huge change
to the buffer.  In that case, to prevent similar problems in the
future, set `undo-outer-limit' to a value that is large enough to
cover the maximum size of normal changes you expect a single
command to make, but not so large that it might exceed the
maximum memory allotted to Emacs.

If you did not execute any such command, the situation is
probably due to a bug and you should report it.

You can disable the popping up of this buffer by adding the entry
(undo discard-info) to the user option `warning-suppress-types',
which is defined in the `warnings' library.
```
Regardless as to how high I set the undo-outer-limit, Telega tends to request over that limit. Increasing undo-outer-limit to 1 million still causes the same issue. 

Aside from this, M-x telega-chat-with still works as intended, with the exception of it being incompatible with evil-mode.

## Steps to Reproduce
1. Install telega through MELPA, compiling TDLib from source.
2. Launch telega through `M-x telega`.

**Comment by zevlg** [comment]
TDLib 1.6.6 is not yet supported, please downgrade to 1.6.4. I’ve also added check for TDLib version into master, it will warn you if TDLib version is unsupported

**Comment by zevlg** [comment]
Telega from master now supports TDLib 1.6.6, please try

**Comment by brettgilio** [comment]
I am closing this, if the behavior persists please reopen.
