### ISSUE TITLE
Make old timestamp format "DD.MM.YY"  configurable

### ISSUE THREAD

**Issue by yuchangyuan** [zevlg/telega.el#186]
## Telega Setup
*OS*: Linux xps13 4.19.115 #1-NixOS SMP Mon Apr 13 08:45:17 UTC 2020 x86_64 GNU/Linux
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10, cairo version 1.16.0)
*Telega*: telega v0.5.4 (TDLib version 1.6.0)

Install method: NixOS

## Current Behavior
timestamp not in current week will always format to "DD.MM.YY", its better to be able to change to "YY-MM-DD" or "YY/MM/DD" or other format.

## Steps to Reproduce
1. open any chat with history more than 1week.
2. timestamp will show as "DD.MM.YY" format.

## Possible Solution
use `add-function` to override `telega-ins--date`

**Comment by zevlg** [comment]
Use this in your configuration to get YY-MM-DD formatting:
```
(defun my-date-ins (orig-ins-func timestamp)
  (telega-ins
   (replace-regexp-in-string
    "\\." "-" (telega-ins--as-string
               (funcall orig-ins-func timestamp)))))

(advice-add 'telega-ins--date :around 'my-date-ins)
```
