### ISSUE TITLE
Guix package emacs-telega cannot locate installed binary if ~/.telega/telega-server exists.

### ISSUE THREAD

**Issue by cireu** [zevlg/telega.el#190]
## Telega Setup
*OS*: GNU Guix
*Emacs*: 26.3
*Telega*: 0.6.27

telega was installed by Guix

## Current Behavior

If `~/.telega/telega-server` is an executable and incompatible with emacs-telega from Guix, emacs-telega cannot run installed server binary.

## Steps to Reproduce

1. Install emacs-telega package from Guix
2. Create an empty file at ~/.telega/telega-server. Give it `+x` permission
3. start telega and telega panicked

## Possible Solution

* Patch the `telega-server--find-bin` in package recipe, force it return a fixed path.

cc @brettgilio

**Comment by brettgilio** [comment]
Fixed in guix, following commit: http://git.savannah.gnu.org/cgit/guix.git/commit/?id=d4b02a6fba7c364ab7c8d257cf9a32134e71ce3e.

Closing
