### ISSUE TITLE
Sanitized Copy/Paste

### ISSUE THREAD

**Issue by divansantana** [zevlg/telega.el#193]
Would be nice to be able to copy and paste out of telega.el without it
containing the date timestamps, users pictures or line
breaks/whitespaces.  Would be a great feature.

**Comment by brettgilio** [comment]
This is still an open issue, the issue is with how the telega buffers are laid out and generated. I think it would take a not insignificant amount of effort to redo this, but I am open to it if somebody wants to help. @zevlg wdyt? Possible as a minor-mode.

**Comment by zevlg** [comment]
`c` and `l` commands are available to copy message text and link. We can close this issue
