### ISSUE TITLE
C-l does not do what I would expect

### ISSUE THREAD

**Issue by divansantana** [zevlg/telega.el#198]
C-l runs the command telega-chatbuf-recenter-1. For me this sometimes
does not do what I would expect C-l to do. The point gets "stuck" in
the middle of the screen. Pushes C-l again I would expect point to go
to top and buffer to move up with it. Directly running (recenter-top-bottom) works though.

It seems telega-chatbuf-recenter-1 changes the behaviour of C-l binding. Perhaps this shouldn't be implemented by default

**Comment by zevlg** [comment]
Could you please check it with master telega (v0.6.30), does `C-l` do what you want?

**Comment by brettgilio** [comment]
Closing. Reopen if the issue persists.
