### ISSUE TITLE
No inline images with emacs 27 running as service

### ISSUE THREAD

**Issue by bwachter** [zevlg/telega.el#201]
With emacs server started as systemd service images are no longer displayed inline in a graphical frame: Just a download button and opening in a new frame.

The old (and expected) behaviour with emacs 26 was a download button in a text frame and inline display in a graphical frame.

**Comment by maddovr** [comment]
I can confirm this with emacs 27.1 stable. No images are displayed inline in the root buffer when starting emacs as a daemon, only when running the standalone emacs.

**Comment by omar-polo** [comment]
I have the same problem, but I've noticed that telega is unable to display images only if emacs is *started* as a daemon (i.e. `emacs --daemon`).  If I start emacs and only then start the daemon (`M-x server-start`), telega is then able to display images.  `(display-images-p)` evaluates to t in both cases.
