### ISSUE TITLE
Telega freezes after message sent: symbol-overlay-refresh

### ISSUE THREAD

**Issue by firmart** [zevlg/telega.el#206]
## Telega Setup
*OS*: `Linux Inspiron 5.7.0-050700-generic #202005312130 SMP Mon Jun 1 01:33:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
*Emacs*: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2020-08-25` 
*Telega*: `telega v0.6.29 (TDLib v1.6.8) (telega-server v0.6.5)`

## Current Behavior

I sent one message to one of my contact and `emacs` freezes.
I ran the command `killall -USR2 emacs` to break the loop and entered in debug mode.
This is what it displayed:

```
Debugger entered--entering a function:
* symbol-overlay-refresh(1 5 0)
  redisplay_internal\ \(C\ function\)()
```
Not very helpful, I know...

Note: after that the infinite loop broken, the message sent is displayed correctly in the chat.

## Steps to Reproduce

1. Reinstall `telega.el`, `telega-server` and `TDLib` to the version stated above. (I cleared `~/.telega` and the installed Melpa package, and reinstalled automatically `telega.el` through `use-package` and `telega-server` through `telega` (step 3)).
2. `M-x telega`
3. Setup `telega`: install `telega-server` and `VoIP` (replied `y` and `y`), setup phone number & login code.
4. Everything fetches correctly, send a message to anyone: infinite loop.

**Comment by zevlg** [comment]
Could you please set `debug-on-quit` to non-nil, reproduce a freeze and press <kbd>C-g</kbd> to get a backtrace to see what is causing loop

**Comment by firmart** [comment]
I have tried before using the `killall` method, however `C-g` does not work in this situation.

**Comment by zevlg** [comment]
Could you please try reproduce this in vanilla start, i.e. not using any additional packages, such as `symbol-overlay`

**Comment by firmart** [comment]
I tried with 
```
emacs -Q -l ~/.emacs.d/elpa/28.0/develop/telega-20200903.1506/telega-autoloads.el -l ~/.emacs.d/elpa/28.0/develop/rainbow-identifiers-20141102.1526/rainbow-identifiers.el -l  ~/.emacs.d/elpa/28.0/develop/visual-fill-column-20200428.816/visual-fill-column-autoloads.el
```

and it works without issue.

I see that I forgot to mention that I use Spacemacs, my apologies. If I load `symbol-overlay`, it still works fine. I have to figure out which part of Spacemacs uses it to track down the issue.

**Comment by firmart** [comment]
@zevlg  Sorry for the delay. I removed `symbol-overlay` and the issue is still here, but maybe a little better: it takes 30s to display the message sent. I noticed that it's rendering which takes time not sending the message (which is instant). I'm going to cross post this issue to spacemacs since there was no issue with `emacs -Q`.

**Comment by brettgilio** [comment]
What is the state of this issue?

**Comment by firmart** [comment]
Sorry for the delay. In the meantime, I gave up `spacemacs` and remove the `symbol-overlay` package. I upgraded telega and TDLib and still experiencing the same issue. Here follows the update of the bug report:

## Telega Setup
*OS*: `Linux Inspiron 5.7.0-050700-generic #202005312130 SMP Mon Jun 1 01:33:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
*Emacs*: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2020-08-25` 
*Telega*: `telega v0.7.1 (TDLib v1.7.0) (telega-server v0.7.0)`



## Current Behavior

I sent one message to one of my contact and `emacs` freezes.
I ran the command `killall -USR2 emacs` to break the loop and entered in debug mode.
This is what it displayed:

```
Debugger entered--entering a function:
* #f(compiled-function () #<bytecode 0x77fbb6b08595747>)()
  debug(error (quit))
  redisplay_internal\ \(C\ function\)()
```
where the bytecode dissassemble to
```
byte code:
  args: nil
0	constant  window-live-p
1	constant  (nil)
2	car-safe  
3	call	  1
4	goto-if-nil 1
7	constant  window-buffer
8	constant  (nil)
9	car-safe  
10	call	  1
11	constant  #<buffer *Backtrace*>
12	eq	  
13	goto-if-nil 1
16	constant  window-total-height
17	constant  (nil)
18	car-safe  
19	call	  1
20	varset	  debugger-previous-window-height
21:1	varref	  debugger-will-be-back
23	goto-if-nil 2
26	constant  set-window-configuration
27	constant  #<window-configuration>
28	call	  1
29	discard	  
30	goto	  4
33:2	constant  window-live-p
34	constant  (nil)
35	car-safe  
36	call	  1
37	goto-if-nil 3
40	constant  window-buffer
41	constant  (nil)
42	car-safe  
43	call	  1
44	constant  #<buffer *Backtrace*>
45	eq	  
46	goto-if-nil 3
49	constant  quit-restore-window
50	constant  (nil)
51	car-safe  
52	varref	  debugger-bury-or-kill
54	call	  2
55	discard	  
56	varref	  debugger-old-buffer
58	set-buffer 
59	discard	  
60:3	constant  nil
61	varset	  debugger-previous-window
63:4	constant  buffer-live-p
64	constant  #<buffer *Backtrace*>
65	call	  1
66	goto-if-nil 7
69	save-current-buffer 
70	constant  #<buffer *Backtrace*>
71	set-buffer 
72	discard	  
73	constant  nil
74	goto-if-nil 5
77	constant  debugger--restore-buffer-state
78	constant  nil
79	call	  1
80	discard	  
81	goto	  6
84:5	constant  nil
85	dup	  
86	varset	  backtrace-insert-header-function
88	varset	  backtrace-frames
90	constant  backtrace-print
91	call	  0
92	discard	  
93:6	unbind	  1
94:7	constant  with-timeout-unsuspend
95	constant  nil
96	call	  1
97	discard	  
98	constant  set-match-data
99	varref	  debugger-outer-match-data
101	call	  1
102	return	  
```

Note: after that the infinite loop broken, the message sent is displayed correctly in the chat.

## Steps to Reproduce


1. Reinstall `telega.el`, `telega-server` and `TDLib` to the version stated above. (I cleared `~/.telega` and the installed Melpa package, and reinstalled automatically `telega.el` through `use-package` and `telega-server` through `telega` (step 3)).
2. `M-x telega`
3. Setup `telega`: install `telega-server` and `VoIP` (replied `y` and `y`), setup phone number & login code.
4. Everything fetches correctly, send a message to anyone: infinite loop.

**Comment by zevlg** [comment]
Is that in vanilla Emacs start?

If everybody had same behaviour, then `telega` would be unusable for everybody.  I simply can't reproduce this, sorry

Search for some of your setup specifics

**Comment by firmart** [comment]
Understandable. I spent two more hours to debug this:
- disable all minor-modes on the chat buffer
- disable the theme
Nothing changed.
I went more radically by disable everything in my setup, and now I have this minimal setup:

```emacs-lisp
;; ~/.emacs
 (require 'package)
 (setq package-enable-at-startup nil)
 (package-initialize)

(use-package telega
  :ensure t
  :config
  (telega-notifications-mode nil)
  (bind-key "C-c t" 'telega))
```

To summarize the progress:
- Vanilla emacs works: `emacs -Q -l ~/.emacs.d/elpa/telega-20201216.1250/telega-autoloads.el -l ~/.emacs.d/elpa/rainbow-identifiers-20141102.1526/rainbow-identifiers.el -l  ~/.emacs.d/elpa/visual-fill-column-20201214.1048/visual-fill-column.el` 
- This also works: `emacs -Q -l ~/.emacs` 
- But the issue is still there with `emacs` alone

I believe now that the site-wide initialization files are responsible...

**Comment by zevlg** [comment]
Is your Emacs responses to <kbd>C-g</kbd> after freeze?  If so, you can set `debug-on-quit` to non-nil and press <kbd>C-g</kbd> after freeze to get the backtrace.

**Comment by firmart** [comment]
As I commented on Sep 27: `C-g` has no effect in this situation. That's why I went with `killall -USR2 emacs` which provides (useless) debug information. I'll compare the difference of `load-history` between `emacs -Q -l ~/.emacs` and `emacs` (diff=10KB). I guess you can remove the bug tag, or even close this issue. I'll update my struggle anyway. Unfortunately, I can't simply `emacs -Q -l ~/.emacs`  (where, this time, `~/.emacs` invokes my heavy configuration), maybe some packages load some site-wide stuffs, but that is beyond my knowledge.

**Comment by zevlg** [comment]
Lets keep this issue open anyway

Probably someone will have same issue and could help us find the roots of it

**Comment by zevlg** [comment]
I've installed fresh spacemacs with Emacs28 from git master, issue does not reproduces

**Comment by firmart** [comment]
Well, my updated bug report (9 days ago) already drop out `spacemacs`. My latest comment provides a minimal non-working example configuration with which the issue is triggered whenever `-Q` is dropped. That leads me to believe that the site-wide startup files are related to this issue (as `-Q` do not load them). The problem is that with my full configuration, the issue is still there even with `-Q`. 

BTW, two months ago I asked a question ([Emacs SE: Paste very specific Unicode in scratch buffer freezes emacs -Q](https://emacs.stackexchange.com/questions/61215/paste-very-specific-unicode-in-scratch-buffer-freezes-emacs-q))  which the referred anomaly is quite similar than [the bug of emacs](https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-01/msg00548.html) you reported and mentioned in the FAQ, but still different though (AFAIK, the fix of the bug is already patched in my version of emacs). 

Maybe I hit a font issue and that explain why is not easily reproducible.

**Comment by firmart** [comment]
I finally fixed the issue ! I got the same problem when using `elfeed`, because some entry's title has some special unicode (e.g. ✨).
See [my emacs.SE answer](https://emacs.stackexchange.com/a/62889/23697) for the solution. Glad I'm back to telega.
