### ISSUE TITLE
Telega bugs on editing deleted message

### ISSUE THREAD

**Issue by SeTSeR** [zevlg/telega.el#207]
## Telega Setup
*OS*: NixOS 21.03 (Okapi)
*Emacs*: 27.1 (x86_64-pc-linux-gnu)
*Telega*: telega v0.6.29 (TDLib v1.6.6) (telega-server v0.6.5)
*MELPA*: 20200903.1506

## Current Behavior

Telega prints message
```
telega-server error: Failed to parse JSON object as TDLib request: Unknown class "telegaInlineQuery"
```
and telega-server may crash.

## Steps to Reproduce

1. Send a message to some chat (my message contained also query to spoilerobot, it can be relevant).
2. Start editing it.
3. While editing it, delete message.
4. Fix query to inline bot in message and send fixed message.

**Comment by zevlg** [comment]
Could you please check this out on telega 0.6.30 ?  It could be fixed there

**Comment by SeTSeR** [comment]
Yes, now telega-server says, that message was not found, so cannot be edited
