### ISSUE TITLE
Error running timer ‘telega-online-status-timer-function’ due to type error

### ISSUE THREAD

**Issue by furiel** [zevlg/telega.el#208]
I receive the following error when starting telega, periodically:
```
Error running timer ‘telega-online-status-timer-function’: (wrong-type-argument number-or-marker-p "126116353")
```

After investigating the problem, I see the error comes from:
https://github.com/zevlg/telega.el/blob/3416f42e35d1ac1d0e1cfbbfe706aef8657fa83d/telega-info.el#L53

Apparently, the type of `tlobj-id` is string (I printed it using `type-of`), which fails `zerop`.

I tried to quick-patch it by adding a
```
  (setq tlobj-id (string-to-number tlobj-id))
```
before that line, which makes that function pass. On the other hand, I still can see occasional error messages like
```
error in process filter: setq: Wrong type argument: stringp, 126116353
error in process filter: Wrong type argument: stringp, 126116353
```
probably from some other part of the code.

Could you please kindly check this problem?

I am using telega from melpa:
```
telega  20200903.1506
telega-server  Version 0.6.5
tdlib  (current master: 3d2067475e0764d4765b41aa372e5c3c10a5af5d)
```

**Comment by zevlg** [comment]
Newest TDLib will be supported in 2 days

**Comment by furiel** [comment]
Thanks for the info! No need to keep this open. I will wait for the new version, and open a new ticket in case I run into trouble.
