### ISSUE TITLE
Telega broke after latest update

### ISSUE THREAD

**Issue by maddovr** [zevlg/telega.el#212]
I updated telega (latest from melpa) and tdlib (git clone). History goes on a loop of "loading" without actually loading anything and chatbuf throws a pp-error. Can't post screenshot publicly as the info can contain private data. Said error appears on each message in chatbuf and each one ends with a (wrong-type-argument number-or-marker-p "148490289")

**Comment by zevlg** [comment]
Looks like you are using old telega with new TDLib 1.6.9.  MELPA sometimes is unable to reload code inplace and Emacs restart is required

Please try on fresh restart and check your `M-x telega-version RET`

**Comment by maddovr** [comment]
Worked just now (odd tho). I did the update this morning and it failed like that, did it just now and there was another, didn't expect, thank you!
