### ISSUE TITLE
How to paste images from clipboard?

### ISSUE THREAD

**Issue by cvanelteren** [zevlg/telega.el#217]
## Telega Setup
*OS*: Linux 5.9.1 Manjaro
*Emacs*: 27.1 
*Telega*: 20201022.157 git

## Current Behavior

File upload from clipboard returns "Selection owner couldn't convert" STRING)

## Steps to Reproduce

1. flamegui make screenshot
2. paste in chat
3. ???
4. profit

**Comment by zevlg** [comment]
What you mean by "paste in chat"?  `C-c C-v` ?

Looks like while doing all these operations someone overwrites your clipboard where flameshot stores the screenshot.

Try screenshot tools built into telega.el.  Set `telega-screenshon-function` to desirable value and in chatbuf press `C-c C-a screenshot RET`, use `C-u` prefix to grab a screen region of the interest

Also see docs for "screenshot" attachment type in https://zevlg.github.io/telega.el/#attaching-media

**Comment by cvanelteren** [comment]
Stupid me. I totally missed the docs link! `C-c C-v` works perfectly fine.
