### ISSUE TITLE
Doesn't show profile photos

### ISSUE THREAD

**Issue by uninhm** [zevlg/telega.el#223]
## Telega Setup
*OS*: Linux unai-gentoo 5.9.1-gentoo #15 SMP Sun Nov 1 20:19:51 -03 2020 x86_64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz GenuineIntel GNU/Linux
*Emacs*: 27.1
*Telega*: telega v0.6.31 (TDLib v1.6.9) (telega-server v0.6.6)

Installed from MELPA

## Current Behavior
Telega doesn't show profile photos, only those who are generated by initials.

**Comment by zevlg** [comment]
Try with 0.7.0 telega from master, still reproduces?

**Comment by brettgilio** [comment]
Closing. Reopen if the behavior is not resolved.
