### ISSUE TITLE
Telega.el shows notifications for unknown channels/groups.

### ISSUE THREAD

**Issue by mikroskeem** [zevlg/telega.el#224]
## Telega Setup
*OS*: Arch Linux
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.17.3)
*Telega*: telega v0.6.31 (TDLib v1.6.9) (telega-server v0.6.6)
*MELPA*: 20201101.1649

```elisp
;; Melpa repository &
(use-package telega
  :ensure t
  :config
  (if (and (string-equal "gnu/linux" system-type) (string-match-p "DBUS" system-configuration-features))
      (telega-notifications-mode 1)))
```

## Current Behavior
Getting notifications for completely unknown channels/groups (haven't joined them in official clients or anything)

## Steps to Reproduce
1) Enable notifications using `(telega-notifications-mode)`
2) Get spammed with notifications:
![image](https://user-images.githubusercontent.com/3490861/99793461-64d4ed80-2b31-11eb-9615-a4804dfa63e3.png)

**Comment by khenarghot** [comment]
Same problem
OS: Fedora 32
Emacs: GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13) of 2019-12-10
Telega: fb057427540ba01c96605dc619a120b4b97cafba (current master)

**Comment by Makima0** [comment]
Same problem
OS: Arch Linux
Emacs: GNU Emacs 28.0.50
Telega: https://github.com/zevlg/telega.el/commit/fb057427540ba01c96605dc619a120b4b97cafba  (current master)
