### ISSUE TITLE
Audio tags don't make when uploading mp3s

### ISSUE THREAD

**Issue by 4DA** [zevlg/telega.el#227]
## Telega Setup
*OS*: Ubuntu 20.04
*Emacs*:  27.1
*Telega*: telega v0.7.0 (TDLib v1.7.0) (telega-server v0.7.0)

## Current Behavior

Audio file artist/title is shown as unknown when uploading audio from telega.el.
When uploading from telegram-desktop everything works as expected.

## Steps to Reproduce

1. Fill in idv3 tags in mp3 file
2. Upload via telega
3. Artist/title are not shown for uploaded track

**Comment by zevlg** [comment]
Could you please share a .mp3 file you have problem with
