### ISSUE TITLE
tty compatibility

### ISSUE THREAD

**Issue by pf10** [zevlg/telega.el#228]
There's an outstanding branch from 2019 for subj #98 which I presume died in the merge. I've had telega.el running on tty on a remote shell for the past couple of months as my primary driver. I would like to integrate and merge my changes upstream. Before I even attempt a cleanup, 
  - Is there any interest from the maintainers in a tty telega?
  - What is the preferred integration strategy? 

My current approach is to simply ignore a lot of visual functionality by cutting off visual branches on (eq window-system nil). For example:
```
(defun telega-ins--content (msg)
  "Insert message's MSG content."
  ;; ...                                                                          
  (pcase (telega--tl-type content)
    (telega-ins "Photo")
    (when window-system
      (telega-ins--photo (plist-get content :photo)
                         msg nil telega-photo-show-details))
    ;; ...                                                                        
    ))
```

**Comment by zevlg** [comment]
What the problem with current telega on tty? I know many people using telega in emacs-nox setup

I myself also run telega on remote Emacs using Blink terminal on iOS

Current telega even runs on non-svg Emacs, see https://github.com/zevlg/telega.el/issues/219

**Comment by brettgilio** [comment]
could you demonstrate some of the concerns you have with the current TTY functionality? What version of telega are you on? As @zevlg said, many people are using tty telega already with minimal friction.

**Comment by zevlg** [comment]
telega supports emacs-nox out of box
