### ISSUE TITLE
Lisp error when client side message ignoring is enabled 

### ISSUE THREAD

**Issue by 4DA** [zevlg/telega.el#229]
When client-side message ignoring is enabled and a lot of messages to be received a `Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")` is triggered.

## Telega Setup
*OS*: gnu/leenoks
*Emacs*: 27.1
*Telega*: v0.7.1

MELPA

**Comment by brettgilio** [comment]
This is usually do to scoping. Could you provide a complete backtrace of the issue by toggling debug-on-error?

**Comment by zevlg** [comment]
Could you please show your client side filtering setup.  User IDs can be shown, Telegram does not allow to get user by id, or you can substitute ids with XXX
