### ISSUE TITLE
proxy is nil but still trying to connect

### ISSUE THREAD

**Issue by 404cn** [zevlg/telega.el#233]
## Telega Setup
*OS*: Manjaro Linux
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
*Telega*: telega v0.7.1 (TDLib v1.7.0) (telega-server v0.7.0)

## Current Behavior

telega-proxies is nil but telega still trying to connecting to proxy, and stuck here.

![telega](https://user-images.githubusercontent.com/24653356/102976924-40f43580-453d-11eb-9fd2-6210c71635fa.png)

**Comment by zevlg** [comment]
Proxy state is saved inside TDLib.  Press <kbd>? n</kbd> in rootbuf to see proxy settings saved in the TDLib.

Probably we should always sync telega proxy settings with the state saved in the TDLib

**Comment by 404cn** [comment]
> Proxy state is saved inside TDLib. Press ? n in rootbuf to see proxy settings saved in the TDLib.
> 
> Probably we should always sync telega proxy settings with the state saved in the TDLib

Yes, I found the proxy I seted, should I reinstall TDLib or is there other ways to clear this rootbuf?

**Comment by zevlg** [comment]
After <kbd>? n</kbd> remove checkmark in "Use Proxy" by moving cursor under ☑ and pressing RET
```
 Use Proxy: ☑ <--- press RET here
```

**Comment by llcc** [comment]
@zevlg I hit `? n`, an error occurred as below:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  >(nil nil)
  #f(compiled-function (cl-x cl-y) #<bytecode -0x1111a152ed2540cf>)("proxies" :@type)
  cl-sort((:@type "proxies" :proxies [(:@type "proxy" :id 2 :server "1.2.3.4" :port 8080 :last_used_date 0 :is_enabled nil :type (:@type "proxyTypeSocks5" :username "rkn" :password "jopa")) (:@type "proxy" :id 3 :server "2.3.4.5" :port 8088 :last_used_date 0 :is_enabled nil :type (:@type "proxyTypeSocks5" :username "rkn" :password "jopa"))] :@extra 4) > :key #f(compiled-function (tl-obj156) #<bytecode -0x12031f868f64e9fd>))
  telega-proxy-last-used((:@type "proxies" :proxies [(:@type "proxy" :id 2 :server "1.2.3.4" :port 8080 :last_used_date 0 :is_enabled nil :type (:@type "proxyTypeSocks5" :username "rkn" :password "jopa")) (:@type "proxy" :id 3 :server "2.3.4.5" :port 8088 :last_used_date 0 :is_enabled nil :type (:@type "proxyTypeSocks5" :username "rkn" :password "jopa"))] :@extra 4))
  telega-ins--network(nil)
  #f(compiled-function () #<bytecode -0xa50f8d37e7c8bc2>)()
  help--window-setup("*Telega Network*" #f(compiled-function () #<bytecode -0xa50f8d37e7c8bc2>))
  telega-describe-network(nil)
  funcall-interactively(telega-describe-network nil)
  command-execute(telega-describe-network)
```
I tried to set `telega-proxies` nil, but it seems telega still uses old proxy. How can I clean the proxy on the tdlib side?
