### ISSUE TITLE
Detect attachment mode automatically

### ISSUE THREAD

**Issue by aragaer** [zevlg/telega.el#245]
Currently when attaching a file I either have to use "send as a file" or some specific mode (like "photo" or "video"). It seems that the client could analyze the file itself and propose the mode based on file. For example when sending an image of "incorrect" size this would mean sending it as a file automatically.

**Comment by zevlg** [comment]
Possible solution: Use `mailcap-file-name-to-mime-type` to detect type of the file using file extension
