### ISSUE TITLE
funcall: Symbol’s function definition is void: telega-markup-org-fmt

### ISSUE THREAD

**Issue by liebkne** [zevlg/telega.el#246]
Trying to use `org` markup, got `funcall: Symbol’s function definition is void: telega-markup-org-fmt` when `RET` was pressed.

## Telega Setup
*OS*: Ubuntu 18.04.5 LTS
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
*Telega*: telega v0.7.8 (TDLib v1.7.0) (telega-server v0.7.4)

## Steps to Reproduce

1. <kbd>C-c C-a</kbd> in a chat buffer.
2. Select `markup`.
3. Select `org`.
4. Write something, <kbd>RET</kbd>

**Comment by zevlg** [comment]
This is ok, citation from README.md:

> telega.el is actively developed, for this reason, some features are not implemented, or they are present just as skeleton for future implementation.
