### ISSUE TITLE
`Debugger entered--Lisp error: (cl-assertion-failed (button "Telega status button is gone"))`

### ISSUE THREAD

**Issue by taohansen** [zevlg/telega.el#25]
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-28

Telega.el latest as of 868abe75a08ea8f48aa424e40834e6869c0485ca commit

Using Doom Emacs latest `develop` branch as of today's date.
`yaourt -S --noconfirm telegram-tdlib`
`cd ~/.emacs.d/.local/packages/quelpa/build/telega/`
`make && make install`

```
~/.doom.d/config.el

(def-package! telega
  :load-path  "~/telega.el"
  :commands (telega)
```
```
~/.doom.d/packages.el

(package! telega :recipe (:fetcher github :repo "zevlg/telega.el"))
```

**Comment by zevlg** [comment]
Telega is not yet ready for compilation.  Remove all corresponding `.elc` files and restart
