### ISSUE TITLE
telega.el renders unicode symbols only in black color

### ISSUE THREAD

**Issue by bit9tream** [zevlg/telega.el#251]
## Telega Setup
*OS*: Gentoo/Linux
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, cairo version 1.16.0)
*Telega*: telega v0.7.8 (TDLib v1.7.0) (telega-server v0.7.4)

## Current Behavior
With dark theme enabled (like modus-vivendi) I cannot see some unicode characters. E.g. this text 𝖘𝖔𝖒𝖊𝖙𝖍𝖎𝖓𝖌 is rendered in pitch black so there is no way to see it. Btw when `telega-emoji-use-images` is set to `nil` there is no issues with this text because Emacs renders everything properly.

## Steps to Reproduce
1. Enable dark theme
2. Set `telega-emoji-use-images` to `t`
3. M-x telega
4. Ask someone to send "𝖘𝖔𝖒𝖊𝖙𝖍𝖎𝖓𝖌" in the chat.

## Possible Solution
Set `telega-emoji-use-images` to `nil`.
Or filter surrogated pairs and render only emojis with telega.el

**Comment by zevlg** [comment]
commentary: Non-emoji symbols from supplementary plane received as surrogated pair is treated as emoji by `telega-server`

Here is comment from telega-dat.c:
```
                /* NOTE: always mark surrogated pairs as emoji, even
                 * if not found in emoji tables, so surrogated pairs
                 * won't apper in strings ever
                 */
```
