### ISSUE TITLE
progn: Symbol’s function definition is void: tracking-mode

### ISSUE THREAD

**Issue by WorldsEndless** [zevlg/telega.el#253]
## Telega Setup
*OS*: openSUSE Tumbleweed
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.22, cairo version 1.16.0)
*Telega*: telega v0.7.12 (TDLib version unknown. Make sure server is running) (telega-server v0.7.5)

## Current Behavior
Run command `telega`, fails with error `progn: Symbol’s function definition is void: tracking-mode`

## Steps to Reproduce

1. emacs -q
2. `M-x telega`
3. progn: Symbol’s function definition is void: tracking-mode

**Comment by zevlg** [comment]
You have non-nil value for`telega-use-tracking-for` and did not installed `tracking` package as described in docstring to `telega-use-tracking-for`

**Comment by WorldsEndless** [comment]
Ah! That was code I copied from somewhere else; i didn't realize there were special instructions involved. I installed tracking.el (from Circe) and things are working beautifully.
