### ISSUE TITLE
Telega: how to enable appindicator when installed from repo (Straight)? 

### ISSUE THREAD

**Issue by WorldsEndless** [zevlg/telega.el#255]
First off, Telega is awesome! I very much would like the appindicators to work, but am not sure what is needed. I've installed from my repos `libappindicator3-dev`, as mentioned in the comments in the code, but don't know whether my telega was built properly -- I did not build it, but installed it from the repo. Is it possible to have libappindicator working with a repo install instead of a custom build? 

## Telega Setup
*OS*: openSUSE Tumbleweed
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.22, cairo version 1.16.0)
*Telega*: telega v0.7.12 (TDLib v1.7.0) (telega-server v0.7.5)

## Current Behavior
No appindicator when Telega installed from repo

## Steps to Reproduce
1.`(telega-appindicator-mode)`
2. Nothing appears
3.

## Possible Solution
Somehow make appindicators possible on repo installs?

**Comment by zevlg** [comment]
To check whether your telega server is compiled with appindicator, run:
```
$ ~/.telega/telega-server -h
Version 0.7.5, with appindicator
...
```
If you have that `with appindicator`, then you compiled all things right.

In case you've installed libappindicator after telega has been already installed, then you need to recompile `telega-server`, use <kbd>M-x telega-server-build RET</kbd> and check results in the "\*Shell Command Output\*" buffer

**Comment by WorldsEndless** [comment]
This was TREMENDOUSLY useful! Thank you! This should definitely be in the documentation. I found that I didn't have appindicators, rebuilt as easy as that, and now I'm good!
