### ISSUE TITLE
appindicator doesn't indicate anything other than telega icon

### ISSUE THREAD

**Issue by WorldsEndless** [zevlg/telega.el#257]
I now have built the server with appindicator support, and sure enough the telega icon appears, and on click it shows its options. However, nothing else sppears -- when I have `telega-appindicator-show-account-name` the name doesn't appear anywhere, and more importantly the number of unread messages doesn't appear anywhere. 

I'm using Polybar; would this be part of the issue? 

## Telega Setup
*OS*: openSUSE Tumbleweed + EXWM
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.22, cairo version 1.16.0)
*Telega*: telega v0.7.12 (TDLib v1.7.0) (telega-server v0.7.5)
*Status Bar*: Polybar 3.5.2

```
      (use-package tracking)

      (use-package telega
	:commands telega
	:custom 
	(telega-use-tracking-for '(any pin unread))
	(telega-chat-use-markdown-formatting t)
	(telega-emoji-use-images t)
	(telega-completing-read-function #'selectrum-completing-read)
	(telega-msg-rainbow-title t)
	(telega-chat-fill-column 75)
	(telega-appindicator-mode t)
	(telega-notifications-mode t)
					      ;:config
	;(setq telega-user-use-avatars nil)
       ) 
```

## Current Behavior
I receive dbus notifications, and on my status bar is the telega icon, but I don't see telega-appindicator-labels

## Steps to Reproduce
1. (telega-notifications-mode)
2. Icon appears and is actionable, but no other information

**Comment by zevlg** [comment]
Account name is only shown in multiple accounts setup, see https://zevlg.github.io/telega.el/#multiple-accounts i.e. `(telega-account-current)` should return non-nil.

Appindicator shows number of chats matching `(or mention (and unread unmuted))` Chat Filter (see https://zevlg.github.io/telega.el/#chat-filters)

I.e. only "important" chats are outlined in the appindicator.  Definition for "important" chat depends on your Telegram settings

If you have `telega-mode-line-mode` enabled, appindicator reflects info shown in the modeline

Also, make sure you have font in the tray area that is able to display symbols from `telega-appindicator-labels`.  In case it can't - modify `telega-appindicator-labels` to strings that can be displayed in the tray area

**Comment by zevlg** [comment]
BTW: there is no such custom variable as `telega-chat-use-markdown-formatting`

Also, set `telega-emoji-use-images` only if running Emacs in daemon mode, see https://zevlg.github.io/telega.el/#settings-for-emacs-as-daemon

**Comment by WorldsEndless** [comment]
(I've removed the irrelevant variables you mentioned above) 

I've tried setting `(telegaq-appindicator-labels nil)` so it would just render plain text numbers, but that also did nothing. I've tried to verify my primary chats are unmuted, which seemed hard to know, but they are definitely not muted on my phone and I never muted them elsewhere, and I also receive dbus notifications for them so I'm pretty sure that is working. Is the appindicator condition customizable? In any case, I'm pretty sure the notification number SHOULD be showing; it showed back when I was using the official telegram client. Any suggestions on how to further debug?

**Comment by zevlg** [comment]
To see is there any "appindicator" commands sent to telega-server set `telega-debug` to non-nil, run telega and switch to \*telega-debug\* buffer and search for "appindicator".  Each "updateUnreadChatCount" should trigger appindicator command to telega-server

**Comment by WorldsEndless** [comment]
That's handy. I see in my log when a message comes:

> 1611959170: OUTPUT: appindicator 11 "label ❶"

However, I don't see anything change.

**Comment by WorldsEndless** [comment]
If appindicator is using SystemNotifier, this might be a known issue with polybar: https://github.com/polybar/polybar/issues/2010

**Comment by WorldsEndless** [comment]
I have verified that it also doesn't update the exwm system tray; it only shows the telega icon without indicators.

**Comment by zevlg** [comment]
afair exwm's system tray is XEMBED-based, which can't display appindicator labels, only icon itself.  `telega` might draw additional info right on the icon itself in that case.  We might add this functionality if we find a good way to do so

**Comment by zevlg** [comment]
And, yes, I think appindicator uses SystemNotifier to update the label text

**Comment by WorldsEndless** [comment]
Excellent to know on both cases. I think that changing the icon image is probably the way the official telegram client does this as well (and is the only thing where they seem to have a leg-up on Telega)

**Comment by zevlg** [comment]
@WorldsEndless please try latest telega from master

**Comment by WorldsEndless** [comment]
Updated it all recently for another reason, and was thrilled to see this in effect! Nice!
