### ISSUE TITLE
customize telega chat date-time string format

### ISSUE THREAD

**Issue by WorldsEndless** [zevlg/telega.el#260]
## Telega Setup
*OS*: openSUSE Tumbleweed
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.22, cairo version 1.16.0)
*Telega*: telega v0.7.12 (TDLib v1.7.0) (telega-server v0.7.5)

## Current Behavior
At the end of older messages I see date-time formatted like this: `31.01.21` . I was surprised to find that was not customizable. Is customizing that currently a work underway somewhere, or should I make a pull request?

**Comment by zevlg** [comment]
Make a pull request
