### ISSUE TITLE
tdlib 1.7.1 is not a valid version

### ISSUE THREAD

**Issue by D4N** [zevlg/telega.el#261]
telega.el specifies version 1.7.1 as the minimum required version of tdlib: https://github.com/zevlg/telega.el/blob/cfe4e938c1942d35b0dee4952de37af688ed6551/telega.el#L14

Unfortunately this does not appear to be a "real" release (see https://github.com/tdlib/td/issues/1403). Could you maybe roll back this requirement as this makes it awkward for distributions to ship tdlib?

**Comment by zevlg** [comment]
See README: This project is developed on two primary branches. The 'releases' branch is kept in compatibility with TDLib major releases. The 'master' branch is for developmental purposes, and utilizes unstable features in TDLib.

use “releases” branch abd tags

**Comment by D4N** [comment]
Zajcev Evgeny <notifications@github.com> writes:

> See README: This project is developed on two primary branches. The 'releases' branch is kept in compatibility with TDLib major releases. The 'master' branch is for developmental purposes, and utilizes unstable features in TDLib.
>

It appears that the master is published to melpa though, which I assume
most people use.

**Comment by zevlg** [comment]
See https://zevlg.github.io/telega.el/#installing-telega-from-melpa

**Comment by zevlg** [comment]
We’ve discussed about scheme how to deal with intermediate TDLib updates and come up with scheme having two branches: for TDLib releases and current TDLib

telega.el master is for TDLib master, and releases branch for latest TDLib releases. We also discussed this with MELPA maintaners

**Comment by D4N** [comment]
That makes sense, thanks for the clarification! I completely forgot about that section or missed it entirely.
