### ISSUE TITLE
Sending some messages causes a telega bug

### ISSUE THREAD

**Issue by kekeimiku** [zevlg/telega.el#264]
## Telega Setup
*OS*:  archlinux
*Emacs*:   emacs28 [pgtk-nativecomp](https://github.com/flatwhatson/emacs/tree/8bcd71bf75672bbcfbb6175301a3552dae4bfb4a) 
*Telega*: telega v0.7.19 (TDLib v1.7.1) (telega-server v0.7.5)

## Current Behavior

![image](https://user-images.githubusercontent.com/36557882/107806476-e3909e00-6da1-11eb-830b-3bf3389e7f84.png)

## Steps to Reproduce

Send in the chat window
```elisp
(setq wl-copy-process nil)
(defun wl-copy (text)
  (setq wl-copy-process (make-process :name "wl-copy"
                                      :buffer nil
                                      :command '("wl-copy" "-f" "-n")
                                      :connection-type 'pipe))
  (process-send-string wl-copy-process text)
  (process-send-eof wl-copy-process))
(defun wl-paste ()
  (if (and wl-copy-process (process-live-p wl-copy-process)) nil
    (shell-command-to-string "wl-paste -t text -n")))
(setq interprogram-cut-function 'wl-copy)
(setq interprogram-paste-function 'wl-paste)
(setq confirm-kill-processes nil)

```

**Comment by zevlg** [comment]
Can't reproduce on my side :(

Could you please set `debug-on-error` to non-nil and trigger the error to get the backtrace

**Comment by zevlg** [comment]
Better to get the backtrace with uncompiled telega, so full info will be available in the backtrace

**Comment by zevlg** [comment]
@kekeimiku have you found the reason or the solution for this issue?  Please share it with us
