### ISSUE TITLE
Missing ZWJ in emojis.alist

### ISSUE THREAD

**Issue by cireu** [zevlg/telega.el#266]
## Telega Setup

*Telega*: f1bb443ce1d24f00203c67b7ebca536832286704

## Current Behavior

Some compound emojis in emojis.alist lacks Zero Width Joiner character, this may cause render engine failed to compose them.

For example: rainbow flag in emojis.alist represent as 🏳🌈, but it should be 🏳️‍🌈

```
(seq-into "🏳🌈" 'vector)
;; => [127987 127752]

(seq-into "🏳️‍🌈" 'vector)
;; => [127987 65039 8205 127752]
```

## Possible Solution

Add missing ZWJ for these emojis, I'm not sure if there are any other emojis should have ZWJ.

**Comment by cireu** [comment]
I think the `:rainbow-flag:` is still not fixed, did you forget to do that?

**Comment by zevlg** [comment]
oh, I've fixed only `:gay-pride-flag:` 😂

**Comment by zevlg** [comment]
Check please latest commit
