### ISSUE TITLE
Invalid function: telega-save-window-start

### ISSUE THREAD

**Issue by wikoion** [zevlg/telega.el#272]
## Telega Setup
*OS*: MacOS 10.15.5
*Emacs*: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
*Telega*: telega v0.7.19 (TDLib v1.7.1) (telega-server v0.7.5)
*MELPA*: 20210212.1021

## Current Behavior
When sending a message I get a small emacs hang with the errors, before the message sends 1/2 seconds later:
`error in process filter: telega-chatbuf--redisplay-node: Invalid function: telega-save-window-start`
`error in process filter: Invalid function: telega-save-window-start`

## Steps to Reproduce
Send a message in Telega

**Comment by zevlg** [comment]
Recompile by hand please, `telega-save-window-start` is a macro defined in the `telega-core.el`

MELPA update sometimes fail to do its job correctly

**Comment by wikoion** [comment]
Ah yeah, that has fixed my issue, weird. I tried reinstalling it twice from melpa with no luck. Thanks :)
