### ISSUE TITLE
Telega's buffer opens and closes immediately right after installation

### ISSUE THREAD

**Issue by kssytsrk** [zevlg/telega.el#282]
## Telega Setup
*OS*: Artix Linux
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
*Telega*: telega v0.7.36 (TDLib v1.7.0) (telega-server v0.7.7)
*MELPA*: 20210406.1309

## Current Behavior
When I execute `M-x telega`, I can see the buffer for a moment and then it's deleted with no errors displayed. The expected behavior is for the buffer to open and stay there to let me read my messages. 

## Steps to Reproduce

1. Install `telegram-tdlib` from AUR.
2. In Emacs, run `M-x package-refresh-contents`, then install `telega` from MELPA (stable).
3. Modify `telega-server-libs-prefix` to point to the right location for tdlib.
4. Build telega-server without VOIP support.
5. Type in the phone number and the login code.
6. Telega closes here, and no matter how many times I reinstall it/reboot Emacs/rebuild telega-server the buffer always closes right away after running `M-x telega`.

No error messages are displayed, and nothing changes with `debug-on-error` and `debug-on-quit` enabled in Emacs (this might be irrelevant but I still decided to include it for the sake of completeness). 
If I delete the `~/.telega` folder, I'm able to build telega-server one more time and input my phone number and login code (it's the right one, I double-checked), and then goto p6 in the list above. 

I have no idea what might cause an issue like that (I've done everything by the manual, except I've used AUR instead of compiling tdlib by hand, but that doesn't seem like a big change) and will be glad to supply any further information about my system's configuration, if needed.

**Comment by zevlg** [comment]
Take a look at `~/.telega/telega-server.log`, it might shed some light on the problem.

Also try running `M-x telega RET` in `emacs -q` env

**Comment by zevlg** [comment]
Also check messages buffer with `C-h e`, telega v0.7.36 (from master) requires at least TDLib 1.7.3 and you have TDLib 1.7.0

See note about master and releases branches this in readme

**Comment by kssytsrk** [comment]
Installed a newer version of TDlib and everything works now, thank you.
