### ISSUE TITLE
Problems with animation playback if fish shell is used

### ISSUE THREAD

**Issue by y0sik** [zevlg/telega.el#286]
## Telega Setup
*OS*: Arch Linux
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
*Telega*: telega v0.7.40 (TDLib v1.7.3) (telega-server v0.7.7)
*MELPA*: 20210424.1730

## Current Behavior
If the value of the `shell-file-name` variable is `"/usr/bin/fish"` (or some other paths to fish), the animations in telega.el are not played. Moreover, Emacs freezes for a certain period of time and errors like `"error in process filter: Opening input file: No such file or directory, /home/<user>/.telega/temp/png-video<random part><number>.png"` appear (`<user>` is the username, `<random part>` will be different for each animation, but the same for all errors of one animation, `<number>` will increase until the end of the animation is reached).

## Steps to Reproduce
1. Make sure that the fish shell is installed (https://fishshell.com)
2. Set the value of the `shell-file-name` variable to "/usr/bin/fish" (or some other path to fish).
3. Open some animation in telega.el (point at it and click RET to play)

## Possible Solution
It seems that the problem is caused by fish, since if you set the value `"/usr/bin/bash"` as the value of `shell-file-name`, the animations are played normally. When setting the value of `telega-debug` to `t`, the lines shown in the picture are written to the `*telega-debug*` buffer. You can see that ^M is considered part of the file name.
![Content of *telega-debug*](https://user-images.githubusercontent.com/59435053/116565158-21a75380-a8f5-11eb-9d2a-9e279fa38267.png)

**Comment by zevlg** [comment]
Should be fixed by https://github.com/zevlg/telega.el/commit/54f4922fa6c3fced17f26684bf83cd897440fb8d
please check it out

**Comment by y0sik** [comment]
Yes, now the animations work fine and Emacs does not hang. Thanks! 
I think this issue can be closed.
