### ISSUE TITLE
[feature request] completion-at-point-functions backends corresponding to the existing company ones

### ISSUE THREAD

**Issue by luishgh** [zevlg/telega.el#289]
Hi, I have been using `telega.el` for a while and it seems only company backends are present for many actions, like completing usernames at the chatbuf input. I think `completion-at-point` should be supported as well, due to the recent popularity of packages like [Corfu](https://github.com/minad/corfu). I'm willing to work on this! Just need to learn a little more about elisp before having the courage to try it. Thanks for the attention!

**Comment by zevlg** [comment]
There are two crucial requirements for the completing system to be included into `telega.el` core:
- Async completion list (re)composition
- Ability to complete things that are not a substring of the completion candidate

AFAIK, cap can't do both of these.  Thats why `company` has been chosen for completions

**Comment by luishgh** [comment]
Could you say one occasion where the second point is needed? I didn't understand it.

**Comment by zevlg** [comment]
I mean cap completions can be written of course, but we can’t include it into telega sources, we can add it as contrib/ package, but not as core part of the telega

**Comment by luishgh** [comment]
Oh, got it. Will try to implement it and tell you here when it's done. Thanks for the explanation @zevlg!
