### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by Difrex** [zevlg/telega.el#29]
Hi,

After successful receiving confirmation code, I receive an error after code input:
`error in process filter: Assertion failed: registered-p`

I'm using GNU Emacs 26.1 at Manjaro GNU/Linux.
tdlib 1.2.1

telega.el from git master.

How to fix this?

**Comment by zevlg** [comment]
Registration with telega is not yet supported, please register in official client and the login with telega

**Comment by Difrex** [comment]
I'm already registered.

Steps to reproduce:
* register on phone
* `M-x telega RET`
* enter phone number
* receive sms with code
* enter code into telega prompt
* get assertion error

**Comment by zevlg** [comment]
Why you receive sms if you already registered? For already registered accounts telegram sends code directly to telegram client

Try running telega, while official telegram client is running on the phone, make sure you use same phone number

Anybody else got this behaviour with already registered accounts?

**Comment by Difrex** [comment]
Oh, that's my fail. I was used a wrong phone number. Thank!
