### ISSUE TITLE
Loops occurring when scrolling in a small chat buffer

### ISSUE THREAD

**Issue by IaH0nii3Re** [zevlg/telega.el#291]
## Telega Setup
*OS*: Artix Linux
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
*Telega*: telega v0.7.44 (TDLib v1.7.4) (telega-server v0.7.10)

## Current Behavior
In telega, when the chat buffer window is of normal size, everything is scrolled well through tab or n, p, but when the window is small, the telega loops over some messages not at all.

## Steps to Reproduce

1. Split windows like in the screenshot
![22_53_23_04_06_2021_screenshot](https://user-images.githubusercontent.com/76109887/120856246-34621780-c588-11eb-8464-3a3cd7be8376.png)
2. Move to chatbuf
3. Try to scroll through the chat with n, p or tab
4. Scroll should loop on some message

My laptop screen size is 13.3 inches, font size on screen is 24.

**Comment by zevlg** [comment]
Triggers when line truncation is disabled.  I.e. `truncate-lines` and `truncate-partial-width-windows` are nil and chatbuf contents does not fit into the window
