### ISSUE TITLE
Some images are not shown in daemon.

### ISSUE THREAD

**Issue by Vonfry** [zevlg/telega.el#296]
According manual, some variables are set as follows:
```
  :hook
  (server-after-make-frame .
    (lambda (&rest _)
      (dolist (symbl '(telega-use-images telega-emoji-font-family
                       telega-emoji-use-images telega-online-status-function))
        (set symbl (eval (car (get symbl 'standard-value)))))))
```

## Telega Setup
*OS*: NixOS 21.05 (Okapi)
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0)
*Telega*: telega v0.7.024 (TDLib v1.7.0) (telega-server v0.7.5)
*MELPA*: 0.7.24

## Current Behavior

Now, the inline images in chatbuf can be displayed. But so are not the users' and chat groups' profile photos. They are ascii characters as well.

## Possible Solution

I cannot find an option to set these. If there is one, it should be added into document.

**Comment by zevlg** [comment]
svg support by Emacs is required. Recompile your Emacs with svg support

svg is heavily utilized by telega

**Comment by Vonfry** [comment]
If I run emacs without daemon under x11, there is no problem. All images can be displayed. So it isn't caused by lacking requirements.

**Comment by Vonfry** [comment]
![image](https://user-images.githubusercontent.com/3413119/123503306-c7bcd300-d684-11eb-8beb-0dfa3dba8240.png)

![image](https://user-images.githubusercontent.com/3413119/123503329-0488ca00-d685-11eb-9a60-18665d85272c.png)

**Comment by zevlg** [comment]
Ah, Emacs as daemon.  You need to set some variables explicitly before loading telega

Setting `telega-use-images` **before** loading telega is essential, because autodetected values for some other variables (including `telega-chat-show-avatars`) depends on the `telega-use-images` value.

**Comment by Vonfry** [comment]
Thanks. It is better If we can make other variables self-adapting with changed `telega-use-images`
