### ISSUE TITLE
leading 0 in version number

### ISSUE THREAD

**Issue by cireu** [zevlg/telega.el#297]
I see leading 0 in the version string, `0.7.023` `0.7.024`, but there's a also a version named `0.7.1` from older commit.

When try to update the telega in Guix, it always complains that I'm downgrading a package.

It's leading 0 a typo? Would you use `0.7.24` instead of `0.7.024`?

**Comment by zevlg** [comment]
0.7.0XX is for stable telega from "releases" branch

0.7.XX is for bleading edge telega from "master" branch

We need a way to distinguish them, we use leading 0 right now

**Comment by cireu** [comment]
Thanks for your answer!
