### ISSUE TITLE
Remove triangles from mode names

### ISSUE THREAD

**Issue by salutis** [zevlg/telega.el#298]
For some reason, Telega buffers and modes have triangles in their names. I am not sure if this is a bug or a feature, but I would like to hide the triangles. Is there a way to customize this aspect of Telega?

<img width="802" alt="Screen Shot 2021-06-30 at 14 28 55" src="https://user-images.githubusercontent.com/1158274/123960377-85aace80-d9af-11eb-9f43-b3610ab5059d.png">

**Comment by zevlg** [comment]
For buffer name `telega-symbol-telegram` is used as prefix.  For modes all lighters are hardcoded and not configurable

Triangle mimics Telegram logo and used for fast recognition of things related to telega.el

**Comment by salutis** [comment]
> For buffer name `telega-symbol-telegram` is used as prefix. 

This is great, `telega-symbol-telegram` is what I was looking for.

Here is my `use-package` configuration for Telega with less decoration:

```elisp
(use-package telega
  :custom
  (telega-filters-custom nil)
  (telega-chat-show-avatars nil)
  (telega-chat-prompt-show-avatar-for nil)
  (telega-symbol-telegram nil)
  (telega-mode-line-string-format '("℡" (:eval (telega-mode-line-unread-unmuted))))
  :config
  (telega-mode-line-mode 1))
```

> For modes all lighters are hardcoded and not configurable

This is unfortunate. I tried to use "diminish" to fix the problem but had no success. So, the only solution for now would be to patch Telega itself, right?

> Triangle mimics Telegram logo and used for fast recognition of things related to telega.el

Ha-ha! I would have never guessed that. My best guess was that the triangle meant to look like some sort of a back button.

**Comment by salutis** [comment]
Today, I found `telega-symbol-mode` described as "*String used for telega modes." It equals "◁" by default. Perhaps the lighters should use that? For completion, I also looked for all the places with a hard-coded "◁" symbol:

```
elpa/telega-20210914.1321/telega-chat.el:(define-derived-mode telega-chat-mode nil "◁Chat"
elpa/telega-20210914.1321/telega-root.el:  `("◁Root" (telega-root-auto-fill-mode
elpa/telega-20210914.1321/contrib/telega-mnz.el:  :lighter " ◁Mnz"
elpa/telega-20210914.1321/telega-modes.el:  :lighter " ◁Squash"
elpa/telega-20210914.1321/telega-modes.el:        (concat "◁Image" (when image-type (format "[%s]" image-type))))
elpa/telega-20210914.1321/telega-modes.el:  :lighter " ◁Edit"
elpa/telega-20210914.1321/telega-modes.el:  :lighter " ◁Highlight"
elpa/telega-20210914.1321/telega-customize.el:(defcustom telega-symbol-mode "◁"
```

**Comment by zevlg** [comment]
> Perhaps the lighters should use that?

Yeah, this symbol has been created exactly for this reason, to be used in mode's lighter.  This is TODO thing

**Comment by salutis** [comment]
@zevlg I see! Thank you so much for the explanation.

**Comment by salutis** [comment]
@zevlg Thank you!
