### ISSUE TITLE
Feature request: support interactively mentioning users without user names

### ISSUE THREAD

**Issue by Merivuokko** [zevlg/telega.el#304]
## Current Behavior

It is quite complicated to mention a user who does not have a Telegram user name. This process involves using Markdown and looking up the user's ID number.

## Possible Solution

Add an interactive command that facilitates mentioning other users. This command could support user name completion in the same way as forwarding messages and creating groups do at the moment.

This feature is very useful in groups where there are people who don't have user names. Those people are not necessarily familar to me so I cannot easily suggest them to add an user name. They even might have a good reason not to add one. As a coordinator I sometimes have to mention these people to more easily get their attention.

**Comment by zevlg** [comment]
`@<name> TAB` supports completion for users not having username, it expands completion to corresponding markdown syntax, you’ve mentioned

If this does not work for you, please supply `M-x telega-version RET` you are using

**Comment by Merivuokko** [comment]
After enabling `company` this works. I think this issue can be closed.

-- 
Aura
