### ISSUE TITLE
Org links aren't rendering

### ISSUE THREAD

**Issue by benthamite** [zevlg/telega.el#319]
## Telega Setup
*OS*:  macOS 11.5.2
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))
*Telega*: telega v0.7.80 (TDLib v1.7.8) (telega-server v0.7.13)

## Current Behavior

Org-mode links are not rendered. I have set `telega-chat-input-markups` to `("org" "markdown1" "markdown2")` and can confirm other markup elements (including italics, monospaced, etc.) work fine. It also doesn't work if the text is wrapped with `<org></org>` (e.g. `<org>[[https://github.com/zevlg/telega.el][telega]] is awesome</org>`).

## Steps to Reproduce

1. Open a chat buffer.
2. `C-c C-a` (`telega-chatbuf-attach`)
3. Select `markup`, then `org`.
4. Insert org link, manually or by invoking `org-insert-link`.

**Comment by zevlg** [comment]
Org links are not supported at the moment, this is todo thing

Supported org syntax is described in the https://zevlg.github.io/telega.el/index-master.html#sending-ordinary-messages

**Comment by zevlg** [comment]
You can keep this issue open, I'll close it once org links support will be implemented in the telega

**Comment by SeTSeR** [comment]
Are there any serious blocks with Org links support or this was just not a priority?

**Comment by zevlg** [comment]
> Are there any serious blocks with Org links support or this was just not a priority?

No, no blockers. They are even partly implemented, see `telega-markup-org--link-fmt`, but this functionality is not integrated into org formatter

**Comment by benthamite** [comment]
Sorry to reopen, but the links aren't working for me.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/5490677/221422334-b4139ed2-9925-48c4-b873-b721b25fd244.png">

Thoughts on what might be going on?

The value of `telega-chat-input-markups` is `'("org")`

telega v0.8.100 (TDLib v1.8.11-a08b1f9) (telega-server v0.8.2)
GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0.1 (Build 22A400)) of 2023-02-23
Org version: "9.6.1"

**Comment by zevlg** [comment]
> Thoughts on what might be going on?
> 
> The value of `telega-chat-input-markups` is `'("org")`
> 
> telega v0.8.100 (TDLib v1.8.11-a08b1f9) (telega-server v0.8.2) GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0.1 (Build 22A400)) of 2023-02-23 Org version: "9.6.1"

org links are only supported since telega 0.8.110, please update telega and check it out

**Comment by benthamite** [comment]
I thought I had pulled the latest commit. In any case, I'm now on v0.8.110 and still not working.

telega v0.8.110 (TDLib v1.8.11-a08b1f9) (telega-server v0.8.2)

**Comment by zevlg** [comment]
> I thought I had pulled the latest commit. In any case, I'm now on v0.8.110 and still not working.
> 
> telega v0.8.110 (TDLib v1.8.11-a08b1f9) (telega-server v0.8.2)

What does `(telega-markup-org-fmt
 "[[https://zevlg.github.io/telega.el/issues/319][link]]")` return for you?

**Comment by benthamite** [comment]
Mmh, after restarting Emacs the links started working. I'm not sure what happened. Apologies for wasting your time.
