### ISSUE TITLE
How do I install or add ol-telega?

### ISSUE THREAD

**Issue by northjayd** [zevlg/telega.el#326]
I don't know where to ask this but I need help
do I put this somewhere?
`(require 'ol-telega)`

in my config or somewhere else?

Or do I do something else. 

I appreciate any help

**Comment by zevlg** [comment]
Yeah, put it in config, make sure telega’s “contrib” directory is in the `load-path`

**Comment by northjayd** [comment]
thank you very much!

**Comment by northjayd** [comment]
Ah so using org-store-link instead did the trick.
Thanks again!
