### ISSUE TITLE
[solution] PP-ERRORs everywhere on tdlib 1.7.10

### ISSUE THREAD

**Issue by ksixty** [zevlg/telega.el#330]
## Telega Setup
*OS*:  Mac OS X 10.15.7
*Emacs*: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15))
*Telega*: telega v0.7.90 (TDLib v1.7.10) (telega-server v0.7.13)

## Current Behavior
As `sender` field has been renamed in a [recent commit](https://github.com/tdlib/td/commit/10c03c450f8d0bcdc9798b72bbb441da65626a45#diff-703ad54d3dfc0b8db2f46f094d88908ed7790b13afca3aab501213ef4891bfd4R808) to `tdlib`, telega's message parser fails now.

## Steps to Reproduce
1. Build the latest `tdlib` version (`a53cb30e99f937cfd64e0266fa558785a184a553` as of now).
2. Re-build `telega-server`.
3. Run telega and see `PP-ERROR`s everywhere.

## Possible Solution

Update parser to match new field name:
```diff
--- a/telega-msg.el
+++ b/telega-msg.el
@@ -1042,7 +1042,7 @@ TL-OBJ could be a \"message\", \"sponsoredMessage\", \"chatMember\" or
                   (sponsoredMessage
                    (list :@type "messageSenderChat"
                          :chat_id (plist-get tl-obj :sponsor_chat_id)))
-                  (message (plist-get tl-obj :sender))
+                  (message (plist-get tl-obj :sender_id))
                   (chatMember (plist-get tl-obj :member_id))
                   ((messageSenderUser messageSenderChat) tl-obj))))
```

**Comment by zevlg** [comment]
TDLib 1.7.10 is not yet supported

**Comment by zevlg** [comment]
Added initial support for TDLib 1.7.10 in the https://github.com/zevlg/telega.el/commit/2474aaf0c9cba06670d3db46b5fe47ce3c6fb97a
