### ISSUE TITLE
TDLib version=1.7.9 < 1.7.10 (min required), please upgrade TDLib and recompile ‘telega-server’

### ISSUE THREAD

**Issue by WorldsEndless** [zevlg/telega.el#331]
I am building tdlib from source and have managed to get it all the way to 1.7.9, but I have no idea where I can get 1.7.10. I am building the latest things I can find on the tdlib master branch, but that is only giving me 1.7.9 . What should I do about this?

## Telega Setup
*OS*: openSUSE Tumbleweed
*Emacs*: GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0)
*Telega*: telega v0.7.100 (TDLib v1.7.9) (telega-server v0.7.13)

## Current Behavior
Reports that I don't have a tdlib version that seems unobtainable

## Steps to Reproduce
1. build tdblib from source, using 'cmake -DCMAKE_BUILD_TYPE=Release ..'
2. telega repo, tried on both master and releases branches: telega-server-build
3. M-x telega
4. error: 'Warning (emacs): TDLib version=1.7.9 < 1.7.10 (min required), please upgrade TDLib and recompile ‘telega-server’'

## Possible Solution
I tried changing the telega-tdlib-min-version manually, but this just broke stuff. Apparently it really does need that version.

**Comment by zevlg** [comment]
Do `git pull && git checkout master` in the tdlib sources dir and recompile it

**Comment by zevlg** [comment]
We can’t stop requiring versions, because this will require us to provide compatibility between different TDLib versions. This is very hard task to do and will make code be clumsy

**Comment by WorldsEndless** [comment]
Yeah, I edited my issue to understand that. I can see that the version is meaningful. 

I pulled the latest from the td repo before this, but will try again.

**Comment by zevlg** [comment]
Make sure you’ve installed newer tdlib and recompiled telega-server with

1.7.10 version is bumped in this particular commit - https://github.com/tdlib/td/commit/a53cb30e99f937cfd64e0266fa558785a184a553

**Comment by WorldsEndless** [comment]
Verified: I can't seem to get past 1.7.9, even with pulling master. Yes, I see the git log has the version bump in it. I'll come back to this with a fresh mind later.

**Comment by zevlg** [comment]
Check you are in the master branch with `git status`.  Switch to master with `git checkout master` if you are on some other or detached branch

**Comment by WorldsEndless** [comment]
It is working again in its own process. Some combination of server rebuilds, git pulls, and tdlib builds has this behaving, at least to working elsewhere. I got pretty tangled in versions of telega, of tdlib, of docker, etc, so my "solution" isn't methodical. But I am no longer having the tdlib version error.
