### ISSUE TITLE
How to completely disable animated emojis and just display the emoji?

### ISSUE THREAD

**Issue by Gira-X** [zevlg/telega.el#335]
## Telega Setup
*OS*: `Darwin blueberry.local 18.7.0 Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64 x86_64`
*Emacs*: `GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2021-04-05`
*Telega*: `telega v0.7.100 (TDLib v1.7.10) (telega-server v0.7.13)`

Installed via MELPA.

When I have a simple 👍 or other emoji message, it gets mapped to an animated emoji (or sticker?) which is not displayed correctly for me. 

![image](https://user-images.githubusercontent.com/15002298/146260711-b942df60-74b3-4de7-b4f1-1a8efece4ec6.png)

I tried to disable the animated emoji because I do not want to see them anyway. I just want to see a one line message with 👍. Is this possible?

I tried to toggle many settings like `telega-emoji-use-images`, `telega-emoji-animated-play`, `telega-animation-play-inline` and others but they all do not change the output.

---

When I hit Enter on the line, it says an error about `tgs2png` but I don't think I can install it trivially on macOS:

```
tgs2png not found in ‘exec-path’, Install from https://github.com/zevlg/tgs2png
```

**Comment by zevlg** [comment]
Better to debug why sticker's thumbnail is not correctly displayed.  BTW: `tgs2png` should be compilable under macos without problems.  But `tgs2png` is not needed to display sticker's thumbnail correctly.

To display just emoji in place of animated emojis messages, redefine `telega-ins--animated-emoji-msg` function, like:
```
(defun telega-ins--animated-emoji-msg (msg)
  (telega-ins (telega-tl-str (plist-get msg :content) :emoji)))
```

**Comment by Gira-X** [comment]
Perfect thanks. Your `(telega-ins--animated-emoji-msg)` works :)

> tgs2png should be compilable under macos without problems.

It depends on `librlottie` and it's not in Homebrew. Possibly https://github.com/SDWebImage/librlottie-Xcode can be used but I am not too experienced with XCode.

**Comment by zevlg** [comment]
Also, you can use dockerized telega-server, image contains all the tools telega needs
