### ISSUE TITLE
(require 'telega) fails if you don't ffmpeg installed

### ISSUE THREAD

**Issue by catern** [zevlg/telega.el#345]
## Telega Setup
*OS*: NixOS 21.05 (Okapi)
*Emacs*: GNU Emacs 28.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
*Telega*: (telega-version fails if you don't have telega-server set up, and I haven't gotten to that yet)

Installation method: MELPA

## Current Behavior
Part of backtrace:
```
  string-match("\\(?:[ \11\n\15]+\\)\\'" nil nil)
  string-trim-right(nil nil)
  string-trim(nil)
  telega-ffplay--check-ffmpeg-output("-codecs" (encoder) "opus" "hevc" "aac" "h264")
  apply(telega-ffplay--check-ffmpeg-output "-codecs" (encoder) ("opus" "hevc" "aac" "h264"))
  telega-ffplay-check-codecs((encoder) "opus" "hevc" "aac" "h264")
  (defconst telega-ffplay--has-encoders (telega-ffplay-check-codecs '(encoder) "opus" "hevc" "aac" "h264"))
  require(telega-ffplay)
```

## Steps to Reproduce

1. Ensure ffmpeg is not on PATH
2. (require 'telega)

**Comment by zevlg** [comment]
What does `M-: (shell-command-to-string "ffmpeg12345") RET` return on your side?

**Comment by catern** [comment]
```
"/run/current-system/sw/bin/bash: ffmpeg12345: command not found
"
```

**Comment by zevlg** [comment]
Thanks, fixed in the master, please check it out.
