### ISSUE TITLE
line-spacing causes horizontal stripes

### ISSUE THREAD

**Issue by 4DA** [zevlg/telega.el#347]
horizontal stripes are visible on images when line-spacing is enabled for telega buffer

## Telega Setup
*OS*: Ubuntu 20.04.1 LTS
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
*Telega*: telega v0.8.2 (TDLib v1.8.0) (telega-server v0.7.13)
*MELPA*: 20220124.1428

## Current Behavior
horizontal stripes are visible when line-spacing is enabled for buffer
![image](https://user-images.githubusercontent.com/364499/151593611-dce3061f-0ef2-4c06-a82f-e128036704d3.png)

## Steps to Reproduce

1. (setq line-spacing 0.2)
2. look at any image in telega buf

**Comment by zevlg** [comment]
With non-0 `line-spacing` the only way to avoid stripes is to insert image as whole thing.  Telega adopts to font size change, but there is no way to adopt non-0 `line-spacing`, thats why we have next code in the `telega-chat-mode-map`:
```
  ;; NOTE: Positive `line-spacing' creates stripes in the images.
  ;; See https://github.com/zevlg/telega.el/issues/347
  (setq line-spacing 0)
```
