### ISSUE TITLE
Broken completion with latest tdlib/telega

### ISSUE THREAD

**Issue by alxchk** [zevlg/telega.el#348]
## Telega Setup
*OS*: Gentoo Linux
*Emacs*: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.16.0)
*Telega*: telega v0.8.10 (TDLib v1.8.1) (telega-server v0.7.13) -- current git master

## Current Behavior

Completion doesn't work.

## Steps to Reproduce

For example, stickers:
1. C-a [TAB] st {completion works} => stickers
2. [TAB] {completion doesn't work} => ??? nothing happens
2.1. Click any key, like "?" => minibuffer has list of sticker packs
2.2 Click first key of name of some sticker pack, then press [TAB] => nothing happens

Same story to forward messages, etc.

**Comment by zevlg** [comment]
Use `(setq telega-completing-read-function 'ido-completing-read)` to have former behaviour

**Comment by alxchk** [comment]
Works, thanks
