### ISSUE TITLE
jump to message throws thread 

### ISSUE THREAD

**Issue by kg04ls** [zevlg/telega.el#350]
When you jump to the message (from reply), and you are in the thread, it exit from thread.
It is not convenient when you are in the comments to the post in the channel.

**Comment by zevlg** [comment]
NOTE: triggers only if message you are jumping to is not already part of the chatbuf

**Comment by zevlg** [comment]
This has been fixed.  When jumping to the message we now check destination thread and reset chatbuf's thread only if threads differs
