### ISSUE TITLE
Many errors after M-x telega

### ISSUE THREAD

**Issue by bigmuncha** [zevlg/telega.el#351]
Many errors after M-x telega

## Telega Setup
*OS*: Ubuntu 20.04.3 LTS
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
*Telega*: telega v0.7.90 (TDLib v1.7.9) (telega-server v0.7.13)

## Current Behavior
I have problem after M-x telega. Freeze while 2-5 minutes and some crashs.

## Steps to Reproduce
1.Open emacs
2. M-x [telega](url)

attach bactrace ant message buffer
[bt1.txt](https://github.com/zevlg/telega.el/files/8061291/bt1.txt)
[bt2.txt](https://github.com/zevlg/telega.el/files/8061293/bt2.txt)
[messages.txt](https://github.com/zevlg/telega.el/files/8061294/messages.txt)

**Comment by zevlg** [comment]
Please update to 0.8.X, this has been fixed

**Comment by bigmuncha** [comment]
thank you, this work
