### ISSUE TITLE
My account was banned, probably because of using telega 

### ISSUE THREAD

**Issue by SteamedFish** [zevlg/telega.el#353]
My telegram account, which have been using for years, was banned by Telegram recently without a reason given.
After sending many emails to Telegram without getting any reply, I purchased a new phone number and registered a new Telegram account.

The new account was fine for about a month, but was banned again today, right after I started to use telega with the new account (I was using only with official clients before, for about a month).

Both my old account and new account have never done anything related to spam/porn/illegal stuff. Just normal chats about Emacs  and coding.

The ID of my old account is 676179719 because it is listed in telega code as patron user.
I lost my new account's ID because I cannot log in and don't know how to get the ID anymore.

**Comment by zevlg** [comment]
Telega can't do anything about this, sorry

The only way is to write to recover@telegram.org or mentioning https://twitter.com/telegram on the Twitter

**Comment by SteamedFish** [comment]
I wrote many emails to them without getting any reply. I'm not going to use Telegram anymore :)

I post an issue here is because, maybe, telega can add a warning about the account risk.

**Comment by zevlg** [comment]
Sad to hear.  I'll add the warning, thank you

**Comment by zevlg** [comment]
Try to DM https://twitter.com/smstelegram

BTW: what is your telega.el version you've been using at the ban time?  Could you also show your telega.el configuration

**Comment by nicolas-graves** [comment]
My configuration comes from Andrew Tropin's RDE, and the version is 0.8.03, commit 733194c : 

`;;; configure-telega.el --- Telegram client in Emacs

;; Author: Andrew Tropin <andrew@trop.in>
;;
;; URL: https://trop.in/rde
;; Keywords: convenience, faces

;;; Commentary:

;; A few keybindings and small adjustments.

;;; Code:

(eval-when-compile (require 'telega) (require 'cape))
(require 'configure-rde-keymaps)
(define-key rde-app-map (kbd "t") 'telega)
(with-eval-after-load
  'telega
  (define-key telega-chat-mode-map (kbd "s-B") 'telega-chat-with)
  (define-key telega-root-mode-map (kbd "s-B") 'telega-chat-with)
  (setq telega-video-player-command
        "/gnu/store/v139yzj5bb4zczp2admh8riwzwh0gwax-mpv-0.35.0/bin/mpv")
  (setq telega-open-file-function 'consult-file-externally)
  (setq telega-open-message-as-file
        '(video audio voice-note animation video-note))
  (autoload 'company-grab "company")
  (setq telega-emoji-company-backend 'telega-company-emoji)
  (defun rde-telega-chat-mode
         ()
         "Add completion at point functions made from company backends."
         (setq-local
           completion-at-point-functions
           (append
             (mapcar
               'cape-company-to-capf
               (append
                 (list telega-emoji-company-backend
                       'telega-company-username
                       'telega-company-hashtag)
                 (when (telega-chat-bot-p telega-chatbuf--chat)
                       '(telega-company-botcmd))))
             completion-at-point-functions)))
  (add-hook 'telega-chat-mode-hook 'rde-telega-chat-mode)
  (setq telega-completing-read-function completing-read-function))
(provide 'configure-telega)

;;; configure-telega.el ends here
`

**Comment by zevlg** [comment]
@nicolas-graves your configuration is totally ok, your combination of telega version and setup does not violate Telegram TOS

There is no way to find out the reason why you've been banned by Telegram and whether or not use of telega is the reason.

The only way to get unbanned is to write to [recover@telegram.org](mailto:recover@telegram.org) describing your case in details.  If there was false positive ban caused by use of telega, they will unban you and tune their heuristics

**Comment by SteamedFish** [comment]
After 4 telegram accounts getting banned myself in a year, and some other people who share similar experiences online, I can conclude the ban is not related to telega. 

From all those experiences, it seems that for some unknown reason, Telegram will mark some devices as "highly suspicious", accounts that have ever login in those devices will automatically be also marked as "highly suspicious" and have very high chances of getting banned. 

My last account that got banned because I was talking about T-Mobile in a public group. There does have many spams that advertise T-Mobile services, I believe, but I was just talking about news about T-Mobile's data breach. I think telegram must use "T-Mobile" as a spam keyword and ban "highly suspicious" accounts that send messages in public groups containing any of their spam keywords. 

Using third party applications such as telega will also get immediately banned if the account is "highly suspicious". This is why I thought that my previous account was banned because of telega. It actually because my devices were already marked as "highly suspicious".

I don't know why my devices/accounts were marked as "highly suspicious" though. I don't think I've done anything that violates telegram's TOS. Sending emails to recover@telegram.org won't get any reply for a reason, nor get accounts unbanned.  

After purchase a new phone number to register a new telegram account, and only use telegram account in new devices such as newly purchased phone and newly purchased PC, my account is totally safe even if using telega and sending "T-Mobile" to public groups. I don't know if reinstalling OS on my previous PC and flushing new ROM on my previous phone will make telegram recognize my previous devices as "new devices", I dare not try because I don't want to lose my fifth telegram account.

Hope this information can help @nicolas-graves.

I have switched my main IM to matrix. Even if telegram's client (both official client and Emacs client) are much convenient to use, and my current telegram account that only used in new devices are currently very safe, I always feel a lot of insecurity using telegram.

**Comment by zevlg** [comment]
@SteamedFish Thank you for such a complete and honest report!

**Comment by Bitnut** [comment]
> My last account that got banned because I was talking about T-Mobile in a public group. There does have many spams that advertise T-Mobile services, I believe, but I was just talking about news about T-Mobile's data breach. I think telegram must use "T-Mobile" as a spam keyword and ban "highly suspicious" accounts that send messages in public groups containing any of their spam keywords.

Very helpful!

**Comment by nicolas-graves** [comment]
Also more info on my side: after 2 bans with around 6 months wait before recovering the account, I don't seem to be banned anymore, despite using telega. Maybe they've filtered out these cases since.
