### ISSUE TITLE
QR code log in is not persistent

### ISSUE THREAD

**Issue by theamazingwaffle** [zevlg/telega.el#356]
## Telega Setup
*OS*: 5.16.14-arch1-1
*Emacs*: 27.2
*Telega*: 0.8.03

Installation method: MELPA Stable

## Current Behavior
After restarting emacs telega asks me to log in again, instead of re-using the previous log in data.

## Steps to Reproduce

1. Install telega as shown in the manual
2. M-x telega
3. Scan the QR code
4. M-x telega-kill and M-x kill-emacs
5. M-x telega
6. Shows log in screen again

## Possible Solution
Using the phone number ~~solves this.~~ seemed to solve this, but it didn't, after successfully logging in, using telega, killing it and then killing emacs, relaunching, it does not work.

## Telega configuration:
```emacs-lisp
(leaf telega
  :pre-setq
  (telega-directory . "~/.local/share/TelegramDesktop/telega/")
  (telega-use-images . t)
  (telega-emoji-font-family . "Apple Color Emoji")
  (telega-emoji-use-images . t)
  (telega-online-status-function . (lambda () (= (random 10) 1)))
  :setq
  (telega-animation-play-inline . 2)
  :config
  (define-key global-map (kbd "C-c t") telega-prefix-map))
```

**Comment by zevlg** [comment]
You need to scan QR code with official Telegram application connected to the internet.  Wait until telega successfully logs in after scanning QR code.  If you kill it before it logs in, then you will need to scan QR code once more time on next login.  Anyway, you can fallback to phone number at any time

**Comment by theamazingwaffle** [comment]
I did in fact wait for it to connect and even used it, after which I closed emacs. On the next day I started it and it asked for login data again.

Also, I launched telega again today, and it doesn't save log in data with the phone number either.

**Comment by zevlg** [comment]
TDLib stores its state in the `telega-database-dir`, make sure this directory does not wipes out between telega launches.
Also, make sure you do not call to `M-x telega-logout RET` between telega launches.

**Comment by zevlg** [comment]
What is your full output from `M-x telega-version RET` while telega is running ? Do you have TDLib 1.8.0 ?

Login procedure is handled and controlled by TDLib, try reporting a bug to TDLib project at https://github.com/tdlib/td/issues

JFYI: tricking with online status is a TOS violation, see 1.4 at the https://core.telegram.org/api/terms

**Comment by theamazingwaffle** [comment]
> JFYI: tricking with online status is a TOS violation, see 1.4 at the https://core.telegram.org/api/terms

Oh, thanks. Is showing always online or always offline also considered tampering?

> What is your full output from M-x telega-version RET while telega is running ? Do you have TDLib 1.8.0 ?

```
telega v0.8.03 (TDLib v1.8.0) (telega-server v0.7.13)
```


I logged in today, and the session was preserved. I think my path was all messed up. Thank you for the quick help.
