### ISSUE TITLE
`user-error: telega error=400: Message must be non-empty ` when sending an inserted image

### ISSUE THREAD

**Issue by a13** [zevlg/telega.el#359]
When I try to send a message which contains a space and an image after the space, I get `user-error: telega error=400: Message must be non-empty` error.

## Telega Setup
*OS*: unknown
*Emacs*: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14), modified by Debian
*Telega*: telega v0.8.11 (TDLib v1.8.1) (telega-server v0.7.13 [docker])

## Current Behavior

I get `user-error: telega error=400: Message must be non-empty`

## Steps to Reproduce

1. insert a space
2. insert an image after the space
3. try to send a message

**Comment by zevlg** [comment]
Fixed, please update and check it out.
