### ISSUE TITLE
Stuck on "fetching chats", high cpu usage

### ISSUE THREAD

**Issue by 18fadly-anthony** [zevlg/telega.el#361]
## Telega Setup
*OS*: NixOS 21.11 (Porcupine)
*Emacs*: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
*Telega*: telega v0.7.031 (TDLib v1.7.9) (telega-server v0.7.5)
*MELPA*: 0.7.31

## Current Behavior
Telega works and I can chat but the main screen always says "Fetching chats..." and it uses 100% of one cpu core.

This is also happening on my laptop (also NixOS) and causes battery drain.

## Steps to Reproduce
1. Install telega via the `epkgs.telega` and `tdlib` NixOS packages
2. Run Telega

**Comment by WorldsEndless** [comment]
This has been happening to me, too, for a while. On exwm my work-around has been to start a seperate emacs process and let it do Telega, and continue other work until it resolves. If it's on the main thread, I don't think it ever finishes. I am not on the latest version, though, so take all this with a lot of salt.

**Comment by mrkiko** [comment]
Hi!
May I ask if you can try with current git HEAD?
Thanks!

**Comment by 18fadly-anthony** [comment]
I no longer use telega sorry
