### ISSUE TITLE
telega server exited abnormally with code 139

### ISSUE THREAD

**Issue by 404cn** [zevlg/telega.el#363]
Cant start telega server.

## Telega Setup
*OS*: Arch Linux, Gnome
*Emacs*: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
*Telega*: telega v0.8.11 (TDLib v1.8.1) (telega-server v0.7.13 [docker])

## Current Behavior

Run M-x telega but it says `[139]telega-server: exited abnormally with code 139`

## Steps to Reproduce

`docker pull zevlg/telega-server:latest`

```elisp
;; https://www.reddit.com/r/emacs/comments/mtb05k/emacs_init_time_decreased_65_after_i_realized_the/
(setq straight-check-for-modifications '(check-on-save find-when-checking))
(setq straight-vc-git-default-clone-depth 1)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'telega)
(setq telega-use-docker t)

```

**Comment by SolAstri** [comment]
how did you solve this?

**Comment by 404cn** [comment]
Sōl Astrī ***@***.***> writes:

> how did you solve this?

I didn't solve this problem, build tdlib from source instead, hope
someone can solve this problem.

-- 
Liu Bo

**Comment by zevlg** [comment]
Set `telega-debug` to non-nil, you will get \*telega-debug\* buffer, where exact docker command will be printed, execute this command in the terminal to find out the reason why it exits.  See similiar issue  starting from https://t.me/emacs_telega/39710

**Comment by 404cn** [comment]
Zajcev Evgeny ***@***.***> writes:

> Set telega-debug to non-nil, you will get *telega-debug* buffer, where exact docker command will be printed, execute this command in the
> terminal to find out the reason why it exits. See similiar issue starting from https://t.me/emacs_telega/39710

Yeah, here is the content of *telega-debug* buffer:

> Fri Mar 31 23:01:04 2023 ---[ telega-server started
> 1680274864: telega-server CMD: docker run  --rm --privileged -i -v /home/liubo/.telega:/home/liubo/.telega -u 1000:1000 --net=host --device /dev/snd:/dev/snd --device /dev/video0:/dev/video0 --device /dev/video1:/dev/video1 -v /dev/shm:/dev/shm -v /etc/machine-id:/etc/machine-id -v /run/user/1000:/run/user/1000 -e XDG_RUNTIME_DIR -v /var/lib/dbus -e XDG_RUNTIME_DIR zevlg/telega-server:latest telega-server -l /home/liubo/.telega/telega-server.log -v 3
> 1680274864: Status: (Disconnected . ) --> (telega-server: starting. . )
> 1680274864: event IN: ***@***.*** "updateOption" :name "version" :value ***@***.*** "optionValueString" :value "1.8.10"))
> 1680274864: event IN: ***@***.*** "updateOption" :name "commit_hash" :value ***@***.*** "optionValueString" :value "c8acf63e02e84f9c5053a4cef253a219dfbe870c"))
> 1680274864: event IN: ***@***.*** "updateAuthorizationState" :authorization_state ***@***.*** "authorizationStateWaitTdlibParameters"))
> 1680274864: Status: (telega-server: starting.. . ) --> (Auth WaitTdlibParameters . )
> 1680274864: docker RUN: docker exec -u 0 6ab4a92667e7 chmod -R o+rw /dev/snd /dev/video0
> 1680274864: OUTPUT: send 23 ***@***.*** "disableProxy")
> 1680274864: OUTPUT: send 476 ***@***.*** "setTdlibParameters" :use_test_dc :false :database_directory "/home/liubo/.telega" :files_directory "/home/liubo/.telega/cache" :database_encryption_key "" :use_file_database t :use_chat_info_database t :use_message_database t :use_secret_chats t :api_id 1234 :api_hash "foo" :system_language_code "en" :device_model "Emacs" :system_version "30.0.50" :application_version "0.8.100" :enable_storage_optimizer nil :ignore_file_names :false)
> 1680274865: SENTINEL: #<process telega-server> -> "exited abnormally with code 139"

But it seems doesn't have any useful things, and here is the content of
telega-server.log:

> [ 3][t 4][1680274864.876255750][Td.cpp:3965][#1][!Td][&td_requests]	Sending update: updateOption {
>   name = "version"
>   value = optionValueString {
>     value = "1.8.10"
>   }
> }
> [ 3][t 4][1680274864.876284360][Td.cpp:3965][#1][!Td][&td_requests]	Sending update: updateOption {
>   name = "commit_hash"
>   value = optionValueString {
>     value = "foo"
>   }
> }
> [ 3][t 4][1680274864.876288175][Td.cpp:3965][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
>   authorization_state = authorizationStateWaitTdlibParameters {
>   }
> }
> [ 3][t 0][1680274864.876303434][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x7f10b4120820
> [ 3][t 0][1680274864.876373291][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 10.000000
> [ 3][t 0][1680274864.876399278][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x7f10b4120860
> [ 3][t 0][1680274864.876448392][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 10.000000
> [ 3][t 0][1680274864.876466512][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x7f10b52b23e0
> [ 3][t 0][1680274864.876509904][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 10.000000
> xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

PS: I use kde wayland and emacs build with pgtk.

--
Liu Bo

**Comment by zevlg** [comment]
> xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

update your `telega`, this path has been added to `telega-docker-volumes` by default

**Comment by 404cn** [comment]
Thanks, it worked after I delete telega docker image and update telega.el.

Zajcev Evgeny ***@***.***> 于2023年4月1日周六 05:36写道：
