### ISSUE TITLE
'telega-chatbuf-attach-photo:'  error

### ISSUE THREAD

**Issue by fenix011** [zevlg/telega.el#365]
## Telega Setup
*OS*: openSUSE Tumbleweed 
*Emacs*: 28.1
*Telega*: telega-20220113.1920 via

 installation method :  MELPA 

## Current Behavior
 what happens is that i expected the image in the clipboard to be pasted. No joy

## Steps to Reproduce
1. copy image
2. paste image
3. see *Messages* :

telega-chatbuf-attach-photo: Wrong type argument: number-or-marker-p, nil
error in process filter: telega-chatbuf--last-msg: Wrong type argument: ewoc, nil
error in process filter: Wrong type argument: ewoc, nil

## Possible Solution
dunno :-)

Thank you, thank you, thank you

**Comment by zevlg** [comment]
Please set `debug-on-error` to non-nil and repeat 1. and 2. to get the backtrace
