### ISSUE TITLE
`telega-msg-resend` is binded by default but isn't defined

### ISSUE THREAD

**Issue by Vonfry** [zevlg/telega.el#366]
## Telega Setup
*Emacs*: `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)`
*Telega*: `telega-20220518.809`

## Current Behavior

`describe-function` (`C-h f`) cannot find function named `telega-msg-resend`.

But it is binded [here](https://github.com/zevlg/telega.el/blob/f5ba3b17c5ac8c7567e3da080fcb3a4e9c38cb94/telega-msg.el#L167).

**Comment by zevlg** [comment]
Thanks, I'll add this command.  For now use `[RESEND]` button in the message header to resend it
