### ISSUE TITLE
Image embedding into SVG is not working in Windows

### ISSUE THREAD

**Issue by alexpandain** [zevlg/telega.el#367]
## Telega Setup
*OS*: Microsoft Windows 11 Pro (v10.0.2009.22000.706)
*Emacs*: GNU Emacs 28.1 (build 52, x86_64-w64-mingw32)
*Telega*: telega v0.8.11 (TDLib v1.8.2 . Make sure server is running) (telega-server v0.8.0)
*MELPA*: 20220319.955

## Current Behavior

Image embedding into SVG isn't working

## Steps to Reproduce

1. Run telega in Windows emacs gui app
2. Eval `(fboundp 'svg-embed-base-uri-image)`
3. profile picture with image willn't show

**Comment by zevlg** [comment]
telega should fallback to slow base64 based embedding under Windows, please check it out.
