### ISSUE TITLE
Unable to downgrade tdlib to desired version

### ISSUE THREAD

**Issue by pati-ni** [zevlg/telega.el#372]
## Telega Setup
*OS*: Debian GNU/Linux bookworm/sid
*Emacs*: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
*Telega*: telega v0.8.44 (TDLib v1.8.5) (telega-server v0.8.0)
*MELPA*: 20220819.506

## Current Behavior

tdlib refuses to start with the latest master tdlib branch version `1.8.5`. There is no version `1.8.4` version tag in the tdlib github, therefore it is not possible to downgrade.

## Steps to Reproduce

1. Launching telega

## Possible Solution

A workaround is to bypass the version check by setting the `telega-tdlib-max-version` to a higher number.

```elisp
(defconst telega-tdlib-max-version "1.8.6")
```

This launches telega fine although it required activation re-registering the device. Seems to be working fine but have extensively tested.

**Comment by zevlg** [comment]
See https://t.me/emacs_telega/35195 for TDLib’s sha1 for 1.8.4
