### ISSUE TITLE
M-x telega telega-server error: Valid api_id must be provided. Can be obtained at https://my.telegram.org [2 times]

### ISSUE THREAD

**Issue by liuliancao** [zevlg/telega.el#374]
M-x telega no message and login info

## Telega Setup
*OS*: Debian GNU/Linux bookworm/sid
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0), modified by Debian
*Telega*: telega v0.8.44 (TDLib v1.8.6) (telega-server v0.8.0)

## Current Behavior
M-x telega failed

## Steps to Reproduce

1. my config
2. `  (use-package telega
    :ensure t
    :config
    (setq telega-proxies
	(list '(:server "127.0.0.1" :port 1089 :enable t
			:type (:@type "proxyTypeSocks5"))))
    )
`
3.M-x telega i have a tip called setTdLib or api_id related, but i dont know how to set , where to set

## Possible Solution

What will i do when i finish install telega-server, telega, tdlib, i have newed an app in telegam and i have app_id, but where can i set, like a json?

**Comment by liuliancao** [comment]
[ 3][t 4][1663945000.491847515][Td.cpp:2947][#1][!Td][&td_requests]	Receive request 1: setTdlibParameters {
  use_test_dc = false
  database_directory = ""
  files_directory = ""
  database_encryption_key = bytes [0] { }
  use_file_database = false
  use_chat_info_database = false
  use_message_database = false
  use_secret_chats = false
  api_id = 0
  api_hash = ""
  system_language_code = ""
  device_model = ""
  system_version = ""
  application_version = ""
  enable_storage_optimizer = false
  ignore_file_names = false
}
[ 3][t 4][1663945000.491930484][Td.cpp:4014][#1][!Td][&td_requests]	Sending error for request 1: error { code = 400 message = "Valid api_id must be provided. Can be obtained at https://my.telegram.org" }
[ 3][t 0][1663945000.491963863][Client.cpp:293][&td_requests]	End to wait for updates, returning object 1 0x56036bcb70c0
[ 3][t 0][1663945000.491998672][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 10.000000


some of log in .telega/telega-server.log

**Comment by zevlg** [comment]
TDLib 1.8.6 is not yet supported

**Comment by liuliancao** [comment]
i checked v1.8.4 from git log of tdlib and i finished build tdlib, it worked, thx a lot!

**Comment by iT-Boyer** [comment]
i have this issue in debian ：
![截屏2023-02-15 19 37 54](https://user-images.githubusercontent.com/4022953/219017223-826e6b2b-945b-404a-9a4f-f4610f5a735a.png)

**Comment by zevlg** [comment]
> i have this issue in debian ： ![截屏2023-02-15 19 37 54](https://user-images.githubusercontent.com/4022953/219017223-826e6b2b-945b-404a-9a4f-f4610f5a735a.png)

Update your telega, TDLib 1.8.11 is supported only since telega v0.8.110
