### ISSUE TITLE
default completing-read function

### ISSUE THREAD

**Issue by theottm** [zevlg/telega.el#375]
## Telega Setup
*OS*: Guix System
*Emacs*: GNU Emacs 28.1.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
*Telega*: telega v0.8.31 (TDLib v1.8.3) (telega-server v0.8.0)
*MELPA*: 0.8.31

## Current Behavior
Why use iod-completing-read as default and not the standard completing-read?

## Possible Solution
(setq telega-completing-read-function 'completing-read)

**Comment by zevlg** [comment]
If default completion system is suitable for telega and ido mode is not enabled, then it will use default completer. See https://github.com/zevlg/telega.el/blob/master/telega-customize.el#L1554 for details
