### ISSUE TITLE
Cannot connect to telga server via docker

### ISSUE THREAD

**Issue by grburgess** [zevlg/telega.el#383]
## Telega Setup
*OS*:  macOS 13.0
*Emacs*: GNU Emacs 28.2 (build 2, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115))
*Telega*: telega v0.8.44 (TDLib v1.8.7) (telega-server v0.8.2 [docker])

## Current Behavior
Upon trying to connect to the telco server via the docker, I get an error:

Status: Auth WaitTdlibParameter

It was working before, but something seems to have changed. 
## Steps to Reproduce
M-x telega

**Comment by zevlg** [comment]
Update your `telega`, TDLib 1.8.7 is not supported by your telega version

**Comment by grburgess** [comment]
uff. I forgot to restart emacs after using straight to pull the latest commits. It is working fine now. Thanks!
