### ISSUE TITLE
Unable to build telega-server in Guix OS

### ISSUE THREAD

**Issue by fenix011** [zevlg/telega.el#386]
## Telega Setup
*OS*: GNU Guix 
*Emacs*: 28.2
*Telega*: latest (as long as we are "rolling-release" )

Installed GNU Guix emacs and emacs-telega packages

## Current Behavior

the build process cannot bind TDlib 

## Steps to Reproduce

1. Install GNU Guix emacs and emacs-telega packages
2. run telega in Emacs
3. ... ?

## Possible Solution

I've tried to setup TDlib library  via  'telega-server-prefix ... (customizing variable ) manually in Emacs, and error message says :

```
Build `telega-server'? (y or n) y
telega-server-build: TDLib is not installed into "/gnu/store/dyhnp2wr4d9g3kxdhasdsvdl848r1wqk-tdlib-1.8.0-1.8.0/lib/". Set ‘telega-server-libs-prefix’ to the TDLib installion path
Wrote /home/fenix/.emacs.d/recentf
```

What am i missing ?

thanks, thanks, thanks !

**Comment by zevlg** [comment]
Have no idea about Guix.

Possibly you need to set `telega-server-libs-prefix` to "/gnu/store/dyhnp2wr4d9g3kxdhasdsvdl848r1wqk-tdlib-1.8.0-1.8.0/" (without "lib" at the end).  telega needs include files as well as library itself

**Comment by fenix011** [comment]
Hi ! I followed your hint... removed the .../lib/ part.

Then  run 'M-x telega ' , and there's another issue while building :

```
Build `telega-server'? (y or n) y
Telega: building telega-server...
telega-server-build: ‘telega-server’ installation failed
```

what am i missing ?

FYI, shell command output shows :

```
make -C server clean
make[1]: Entering directory '/home/fenix/.emacs.d/elpa/telega-20221101.813/server'
/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/sh: line 1: pkg-config: command not found
make[1]: Leaving directory '/home/fenix/.emacs.d/elpa/telega-20221101.813/server'
make -C server install
make[1]: Entering directory '/home/fenix/.emacs.d/elpa/telega-20221101.813/server'
/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/sh: line 1: pkg-config: command not found
cc -I/gnu/store/dyhnp2wr4d9g3kxdhasdsvdl848r1wqk-tdlib-1.8.0-1.8.0//include -Wall -g -pthread -o telega-server telega-server.c telega-dat.c telega-pngext.c -L/gnu/store/dyhnp2wr4d9g3kxdhasdsvdl848r1wqk-tdlib-1.8.0-1.8.0//lib -Wl,-rpath,/gnu/store/dyhnp2wr4d9g3kxdhasdsvdl848r1wqk-tdlib-1.8.0-1.8.0//lib -ltdjson
make[1]: cc: No such file or directory
make[1]: *** [Makefile:35: telega-server] Error 127
make[1]: Leaving directory '/home/fenix/.emacs.d/elpa/telega-20221101.813/server'
make: *** [Makefile:12: server-reinstall] Error 2
```

Thanks, Thanks, Thanks !

**Comment by SeTSeR** [comment]
I think now this issue is a bit obsolete, since Guix has `emacs-telega-server` package, alongside with mentioned `emacs-telega`.

**Comment by SeTSeR** [comment]
You may also build latest telega from master with Guix itself like this:
```sh
guix package -i emacs-telega —with-branch=emacs-telega=master —with-branch=emacs-telega-server=master —with-commit=tdlib=c8acf63e0 —with-input=tdlib-1.8.0=tdlib
```

However, beware that telega from master uses more recent tdlib, that Guix has, so you will need it to build it from source also. And I’m not entirely sure, how this would behave during updates. I suppose, it’d be better to use fixed commits instead of branch specifiers to avoid such problems.
