### ISSUE TITLE
contrib/telega-transient.el not loading

### ISSUE THREAD

**Issue by sarg** [zevlg/telega.el#397]
## Telega Setup
*OS*: Guix System
*Emacs*: GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
*Features*: svg 
*Telega*: telega v0.8.100 (TDLib v1.8.10-GITDIR-) (telega-server v0.8.2)
*MELPA*: 0.8.100

## Current Behavior
`(require 'telega-transient)` fails with `Mandatory ARGLIST is missing`

## Possible Solution
```diff
--- a/contrib/telega-contrib.el
+++ b/contrib/telega-contrib.el
@@ -63,7 +63,7 @@
 ;; single vector, see `magit-diff' as example
 (defmacro telega-transient-define-prefix-by-keymap (name label keymap)
   (declare (indent 2))
-  `(transient-define-prefix ,name
+  `(transient-define-prefix ,name nil
      ,(format "Transient command for `%S' keymap." keymap)
      [,label
       ,@(mapcar (lambda (kf)
```

**Comment by zevlg** [comment]
Thanks, fixed in the master!
