### ISSUE TITLE
[FR]  load newer messages if telega-image reach first/last loaded image

### ISSUE THREAD

**Issue by qingshuizheng** [zevlg/telega.el#398]
Hi zevlg,

This is a feature discussed Last October in telega: https://t.me/emacs_telega/37276 :

Current Behavior:
When navigate images in `telega-image-mode` with `telega-image-prev` and `telega-image-next`, if `telega-image-mode` reach to the first or last loaded image, it just stops and won't load newer image of chatbuf automatically.

FR:
Trigger loading newer images when `telega-image-mode` reaches to the first or last loaded image.

Thanks, 😄 
Zheng.

**Comment by zevlg** [comment]
This already has been done, please update telega to utilize this functionality

**Comment by qingshuizheng** [comment]
Ah thanks! Sorry I missed that. I will close it.
