### ISSUE TITLE
Telega folder options don't work

### ISSUE THREAD

**Issue by fleurc** [zevlg/telega.el#415]
TDlib throws an unknown class request error when trying to create a folder.

## Telega Setup
*OS*: Fedora Linux 38 (Sway)
*Emacs*: GNU Emacs 28.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
*Features*: svg ffmpeg tgs2png 
*Telega*: telega v0.8.120 (TDLib v1.8.14-1da3955) (telega-server v0.8.2)

## Current Behavior

When creating a folder, Telega gives the following error:
`telega-server--call: telega error=400: Failed to parse JSON object as TDLib request: Unknown class "createChatFilter"`

Telega also doesn't seem to import existing folders from other Telegram clients.
I have built and compiled Tdlib from source as suggested twice, using the C++ build
generation. It gave no errors when created.

## Steps to Reproduce

1. Open Telega, and have telega-server running;
2. Use telega-folder-create to create a folder
3. Select name, friends and icon;
4. Error.

**Comment by zevlg** [comment]
TDLib 1.8.14 is not yet supported

**Comment by fleurc** [comment]
What's the TDLib version that i should compile then?

**Comment by fleurc** [comment]
If in 1w or 2w it's added i can simply wait i feel. If not then i'll downgrade the version of TDLib. Will close for now.

**Comment by zevlg** [comment]
> If in 1w or 2w it's added i can simply wait i feel. If not then i'll downgrade the version of TDLib. Will close for now.

Added support for TDLib 1.8.14 by the https://github.com/zevlg/telega.el/commit/c09a8f3ca8cd921e11c8bc256066364c84eac023

**Comment by fleurc** [comment]
The latest commit has solved the problem beautifully
