### ISSUE TITLE
Header in telega-root accumulates qualifiers

### ISSUE THREAD

**Issue by Sbozzolo** [zevlg/telega.el#43]
Every time I press return on the various filter names on the header of telega-root, the descriptor in the parentheses in the dashed line gets that qualifier appended. For instance, with all:

![2019-01-31 10 48 21](https://user-images.githubusercontent.com/9167485/52077234-bd4a8d80-254d-11e9-93bb-59e117a98351.png)

**Comment by zevlg** [comment]
Fixed in 
https://github.com/zevlg/telega.el/tree/telega-with-inserters

Will be available in 0.3.X version
