### ISSUE TITLE
Telega stuck on history loading

### ISSUE THREAD

**Issue by cvanelteren** [zevlg/telega.el#430]
Recently upgraded my doom emacs to 29.1 which broke my telega setup. Writing new messages works fine but I cannot see any history. 

## Telega Setup
*OS*: Linux  6.4.9 (ARCH)
*Emacs*: GNU Emacs 29.1 (doom)
*Telega*:  0.8.1.4.1 TDLIB 1.8.16-470c36c

## Current Behavior
Opening a chat reads `history loading`. Writing new messages works but history nevery loads.

## Steps to Reproduce

1.  download install emacs 29.1 with doom
2. install telega through melpa
3. open telega

**Comment by zevlg** [comment]
To use  TDLib 1.8.16 update your telega to 0.8.160+ version

**Comment by cvanelteren** [comment]
Thanks for the quick reply. Fix works. Closing!
