### ISSUE TITLE
Multi-line messages on MacOS have inconsistent indentation

### ISSUE THREAD

**Issue by graynk** [zevlg/telega.el#435]
Hi! Thanks for the work on the client. It works perfectly on Linux, but on Mac I have some issues. One of those is: multi-line messages (like multi-line text or stickers) get broken up after the first line, because the indentation is different after the avatar. See attached screenshot:
<img width="254" alt="image" src="https://github.com/zevlg/telega.el/assets/3626328/e61e76e3-4256-4040-b723-7f76e7a8c61f">
<img width="647" alt="image" src="https://github.com/zevlg/telega.el/assets/3626328/c500a34d-1d58-4175-a4f0-f50694781aeb">

## Telega Setup
*OS*:  macOS 13.5.1
*Emacs*: GNU Emacs 29.1 (build 1, aarch64-apple-darwin22.6.0, NS appkit-2299.70 Version 13.5.1 (Build 22G90))
*Features*: svg webp ffmpeg 
*Telega*: telega v0.8.163 (TDLib v1.8.19-b41a51f) (telega-server v0.8.2)

## Current Behavior
Indentation of messages does not take into account the width of the avatar

**Comment by zevlg** [comment]
Use fixed width font

**Comment by graynk** [comment]
Ah! Makes sense, sorry for the trouble.
