### ISSUE TITLE
custom notifications

### ISSUE THREAD

**Issue by KonstantinDjairo** [zevlg/telega.el#436]
is there any way to redirect the notifications to libnotify or [herbe](https://github.com/dudik/herbe)?

**Comment by zevlg** [comment]
telega notifications uses Emacs built-in `notifications` package to feed notifications to dbus.  If libnotify is able to act as org.freedesktop.Notifications D-Bus service, then there will be no problem.

Also, telega has `telega-alert.el` contrib package, which redirects notifications into `alert.el` package, which can use different notifications backends.  `libnotify` is known backend for alert.el, I have not heard about herbe backend for alert.el, but it could be written I think

**Comment by KonstantinDjairo** [comment]
thanks, i'll take a look into alert.el

**Comment by KonstantinDjairo** [comment]
alright, it worked
here's the code:
> https://github.com/KonstantinDjairo/emacs.d/blob/main/telega-misc/notification.el

this runs a modified version of alert.el, which is contained within my repo as well
