### ISSUE TITLE
The bot has blocked me 

### ISSUE THREAD

**Issue by OrionRandD** [zevlg/telega.el#437]
I am a long time member of the telega.el channel and yesterday the idiot robot has blocked me...
I cannot send any message in it anymore. I have already filled a complaint, but the bot keeps blocking me...
Such an anoyance...

Cypher                                                                       
    append: Symbol’s value as variable is void:
    telega-emoji-company-backend
    ⛔Failed to send: USER_BANNED_IN_CHANNEL                               07:11⛔

**Comment by zevlg** [comment]
`telega-emoji-company-backend` is obsolete in the telega 0.8.200

as to your block, I don't see any restrictions on you in the https://t.me/emacs_telega group

Possibly you got restricted by Telegram, check your status in the https://t.me/SpamBot official bot
