### ISSUE TITLE
Improve support for RTL languages

### ISSUE THREAD

**Issue by dov** [zevlg/telega.el#45]
Currently when inputting text in an RTL language (e.g. Hebrew) the input base direction is fixed at LTR. This should be changed to determine the input direction from the line input. A typical heuristic is to determine it from the first "strong character" in the unicode bidirectional algorithm sense. The paragraph direction should then be changed through a call to `current-bidi-paragraph-direction` according to the text direction.

**Comment by zevlg** [comment]
Oh, I have no Idea how to approach it, this should be done by some active RTL user

**Comment by dov** [comment]
I investigated this a bit and I found that the reason that the row stays LTR even though the first character is RTL is because of the hidden string `no-value` in the begging of the prompt. Even though this string is invisible, it influence emacs bidi algo. Once I changed this string to something neutral (pun intended) "!!##$$", then Hebrew works much more natural.

**Comment by dov** [comment]
I needed one more change to make each line processed separately:

```
(add-hook 'telega-chat-mode-hook
          (lambda () 
            (setq bidi-paragraph-start-re "^")
            (setq bidi-paragraph-separate-re "^"))
          t)
```

With this and the hidden string change, RTL behaves as expected.

**Comment by zevlg** [comment]
> I investigated this a bit and I found that the reason that the row stays LTR even though the first character is RTL is because of the hidden string `no-value` in the begging of the prompt. Even though this string is invisible, it influence emacs bidi algo. Once I changed this string to something neutral (pun intended) "!!##$$", then Hebrew works much more natural.

Nice! thanks, I'll do the same in 0.3.X

**Comment by zevlg** [comment]
@dov Could you please check, does https://github.com/zevlg/telega.el/commit/5d673791161db5b1242758b943cff98ce98f79a0 breaks RTL or everything is ok?

**Comment by dov** [comment]
Sorry for the delay in answering.

I just tested the branch telega-with-inserters df1a8d598 and it does *not* work as it should for RTL:

1. When inserting the line direction is not according to the first strong character. To test on your own copy the characters ALEPH (א) and then insert three dots. If ok, you'll get "...A". If not ok, you'll get "A..."
2. The way that icons are split between tow lines doesn't work for RTL texts:

![foo](https://user-images.githubusercontent.com/338235/55675003-c268e780-58c4-11e9-9093-6d3e1e929931.png)

**Comment by zevlg** [comment]
@dov ah, 2. might be not that easy to fix :(.  One solution might be to use one-line avatar version

 For 1. I'll investigate further 

thanks for the feedback!
