### ISSUE TITLE
Add markdown authoring support

### ISSUE THREAD

**Issue by dov** [zevlg/telega.el#46]
Currently when authoring a message with markdown, it is not encoded properly when send to the server, and the raw input is sent.

This may be tested by the following input and comparing with the GUI client:

        This is `verbatim`.
        This is **bold**.
        This is __italics__.
        ```
        This is multi
        line 
        verbatim
        ```

(I think these are all the markups supported in Telegram).

**Comment by zevlg** [comment]
Use `C-u RET` instead of simple `RET` to apply markdown formatting to the input

**Comment by dov** [comment]
Thanks! I missed that. I turned on `telega-chat-use-markdown-formatting` permanently, since that is my prefered default behavior.
