### ISSUE TITLE
Telega traps on launch due to a Transient macro-expansion failure

### ISSUE THREAD

**Issue by rudolf-adamkovic** [zevlg/telega.el#472]
## Telega Setup

*OS*: MacOS Sonoma 14.4.1

*Emacs*: `GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin23.4.0, NS appkit-2487.50 Version 14.4 (Build 23E214)) of 2024-04-24`

*Telega*: `M-x telega-version` does not work, as it traps with the same error as `M-x telega RET`; per `M-x list-packages RET`, the version is `20240410.928`

## Steps to Reproduce

1. Launch Emacs compiled from `main`.
2. Enable MELPA and install Telega using =package-install=.
3. `M-x telega RET`.

## Curent Behavior

```
internal-macroexpand-for-load: Eager macro-expansion failure: (error "transient-define-*: Interactive form missing")
```

## Expected Behavior

Running Telega.

**Comment by zevlg** [comment]
What is your `transient` version ?

**Comment by cnsunyour** [comment]
Same issue. 
It seems to be caused by https://github.com/magit/transient/commit/7e827c31d63e6aaff6511c33f436dbcba619de4e

**Comment by rudolf-adamkovic** [comment]
> What is your `transient` version ?

```
Package transient is built-in.

     Status: Built-In.
    Version: 0.6.0
    Summary: Transient commands
Required by: telega-20240410.928, magit-20240423.2030, git-commit-20240415.1544,
               geiser-guile-20240314.1950, ement-0.15, cider-20240423.1541
Other versions: 20240421.1737 (installed), 20240421.1737 (melpa), 0.6.0 (melpa-stable), 0.6.0 (gnu).
```
