### ISSUE TITLE
Messages with URLs do not display properly after most recent update

### ISSUE THREAD

**Issue by benthamite** [zevlg/telega.el#475]
After updating to the latest commit (`3061519`), messages containing URLs are not shown correctly, e.g.:

<img width="845" alt="image" src="https://github.com/zevlg/telega.el/assets/5490677/be41961a-7e0a-427d-9836-bb28c084258a">

I tried updating TDlib to the latest commit (`77b3479`), `M-x telega-server-build`, and restarting Emacs, but the problem persists.

## Telega Setup
*OS*:  macOS 14.2.1
*Emacs*: GNU Emacs 29.3 (build 2, aarch64-apple-darwin23.2.0, NS appkit-2487.30 Version 14.2.1 (Build 23C71))
*Features*: imagemagick svg webp ffmpeg 
*Telega*: telega v0.8.255 (TDLib v1.8.28-77b3479) (telega-server v0.8.2)

**Comment by zevlg** [comment]
Please set `debug-on-error` to non-nil and trigger the error to get the backtrace

**Comment by benthamite** [comment]
[backtrace.txt](https://github.com/zevlg/telega.el/files/15193807/backtrace.txt)

(Adding as an attachment because it is too long to fit in a message, and I don’t know where to truncate it.)

**Comment by zevlg** [comment]
Thanks, I see the reason, will fix it soon.  BTW, could you please show your value for `image-types`

**Comment by benthamite** [comment]
Yes, it is `(heic svg imagemagick webp png gif tiff jpeg xpm xbm pbm)`.
