### ISSUE TITLE
telega-server--idle-timer-function error

### ISSUE THREAD

**Issue by OrionRandD** [zevlg/telega.el#479]
I am getting this error all the time I open telega in my emacs:

Error running timer ‘telega-server--idle-timer-function’: (wrong-type-argument stringp nil)

=> GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-05-15, modified by Debian
=> telega v0.8.290 (TDLib v1.8.29-fd3154b) (telega-server v0.8.2)

**Comment by zevlg** [comment]
Set `debug-on-error` to non-nil and trigger the error to get the backtrace

**Comment by OrionRandD** [comment]
> Set `debug-on-error` to non-nil and trigger the error to get the backtrace

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  telega-ins--sponsored-message((:@type "sponsoredMessage" :message_id 2251799812636674 :is_recommended nil :can_be_reported t :content (:@type "messageText" :text (:@type "formattedText" :text "Ganhe R$600/semana usando a alta do dólar, 10 minu..." :entities [])) :sponsor (:@type "messageSponsor" :url "https://t.me/prof_VivadeRenda" :info "") :title #("  VIVA DE RENDA SINAIS OFICIAL   " 0 2 (telega-emoji-p t telega-display " ") 31 33 (telega-emoji-p t telega-display " ")) :button_text "VIEW CHANNEL" :accent_color_id 2 :background_custom_emoji_id "0" :additional_info ""))
  telega-button--insert(telega-sponsored-msg (:@type "sponsoredMessage" :message_id 2251799812636674 :is_recommended nil :can_be_reported t :content (:@type "messageText" :text (:@type "formattedText" :text "Ganhe R$600/semana usando a alta do dólar, 10 minu..." :entities [])) :sponsor (:@type "messageSponsor" :url "https://t.me/prof_VivadeRenda" :info "") :title #("  VIVA DE RENDA SINAIS OFICIAL   " 0 2 (telega-emoji-p t telega-display " ") 31 33 (telega-emoji-p t telega-display " ")) :button_text "VIEW CHANNEL" :accent_color_id 2 :background_custom_emoji_id "0" :additional_info ""))
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_108>((:@type "sponsoredMessage" :message_id 2251799812636674 :is_recommended nil :can_be_reported t :content (:@type "messageText" :text (:@type "formattedText" :text "Ganhe R$600/semana usando a alta do dólar, 10 minu..." :entities [])) :sponsor (:@type "messageSponsor" :url "https://t.me/prof_VivadeRenda" :info "") :title #("  VIVA DE RENDA SINAIS OFICIAL   " 0 2 (telega-emoji-p t telega-display " ") 31 33 (telega-emoji-p t telega-display " ")) :button_text "VIEW CHANNEL" :accent_color_id 2 :background_custom_emoji_id "0" :additional_info ""))
  mapc(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_108> [(:@type "sponsoredMessage" :message_id 2251799812636674 :is_recommended nil :can_be_reported t :content (:@type "messageText" :text (:@type "formattedText" :text "Ganhe R$600/semana usando a alta do dólar, 10 minu..." :entities [])) :sponsor (:@type "messageSponsor" :url "https://t.me/prof_VivadeRenda" :info "") :title #("  VIVA DE RENDA SINAIS OFICIAL   " 0 2 (telega-emoji-p t telega-display " ") 31 33 (telega-emoji-p t telega-display " ")) :button_text "VIEW CHANNEL" :accent_color_id 2 :background_custom_emoji_id "0" :additional_info "")])
  seq-do(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_108> [(:@type "sponsoredMessage" :message_id 2251799812636674 :is_recommended nil :can_be_reported t :content (:@type "messageText" :text (:@type "formattedText" :text "Ganhe R$600/semana usando a alta do dólar, 10 minu..." :entities [])) :sponsor (:@type "messageSponsor" :url "https://t.me/prof_VivadeRenda" :info "") :title #("  VIVA DE RENDA SINAIS OFICIAL   " 0 2 (telega-emoji-p t telega-display " ") 31 33 (telega-emoji-p t telega-display " ")) :button_text "VIEW CHANNEL" :accent_color_id 2 :background_custom_emoji_id "0" :additional_info "")])
  telega-chatbuf-footer-ins-sponsored-messages()
  (progn (when telega-chatbuf--messages-compact-view (telega-ins "\n")) (telega-chatbuf-footer-ins-sponsored-messages) (telega-chatbuf-footer-ins-prompt-delim t t) (telega-chatbuf-footer-ins-action-bar) (telega-chatbuf-footer-ins-active-vvnote) (telega-chatbuf-footer-ins-active-video-chat) (telega-chatbuf-footer-ins-active-stories) (telega-chatbuf-footer-ins-pinned-stories) (telega-chatbuf-footer-ins-invite-forbidden-users) (telega-chatbuf-footer-ins-auto-delete-messages) (telega-chatbuf-footer-ins-reply-markup-buttons) (telega-chatbuf-footer-ins-restriction-reason) (telega-chatbuf-footer-ins-bot-description) (telega-chatbuf-footer-ins-join-button) (telega-chatbuf-footer-ins-aux-plist))
  telega-ins--insexp((progn (when telega-chatbuf--messages-compact-view (telega-ins "\n")) (telega-chatbuf-footer-ins-sponsored-messages) (telega-chatbuf-footer-ins-prompt-delim t t) (telega-chatbuf-footer-ins-action-bar) (telega-chatbuf-footer-ins-active-vvnote) (telega-chatbuf-footer-ins-active-video-chat) (telega-chatbuf-footer-ins-active-stories) (telega-chatbuf-footer-ins-pinned-stories) (telega-chatbuf-footer-ins-invite-forbidden-users) (telega-chatbuf-footer-ins-auto-delete-messages) (telega-chatbuf-footer-ins-reply-markup-buttons) (telega-chatbuf-footer-ins-restriction-reason) (telega-chatbuf-footer-ins-bot-description) (telega-chatbuf-footer-ins-join-button) (telega-chatbuf-footer-ins-aux-plist)))
  telega-chatbuf--footer-update()
  telega-chatbuf--chat-update()
  telega-chat--update((:@type "chat" :id -1001099505434 :type (:@type "chatTypeSupergroup" :supergroup_id 1099505434 :is_channel t) :title "Hacker News" :photo (:@type "chatPhotoInfo" :small (:@type "file" :id 1236 :size 2606 :expected_size 2606 :local (:@type "localFile" :path "/home/vagner/.telega/profile_photos/80457191186875..." :can_be_downloaded t :can_be_deleted t :is_downloading_active nil :is_downloading_completed t :download_offset 0 :downloaded_prefix_size 2606 :downloaded_size 2606) :remote (:@type "remoteFile" :id "AQADBAADC6wxG-RpKgsACAIAA-bQ0ekW____KYjqS6QRg-A1BA" :unique_id "AQADC6wxG-RpKgsAAQ" :is_uploading_active nil :is_uploading_completed t :uploaded_size 2606) :telega-file-recency 1716642357) :big (:@type "file" :id 1237 :size 0 :expected_size 0 :local (:@type "localFile" :path "" :can_be_downloaded t :can_be_deleted nil :is_downloading_active nil :is_downloading_completed nil :download_offset 0 :downloaded_prefix_size 0 :downloaded_size 0) :remote (:@type "remoteFile" :id "AQADBAADC6wxG-RpKgsACAMAA-bQ0ekW____KYjqS6QRg-A1BA" :unique_id "AQADC6wxG-RpKgsB" :is_uploading_active nil :is_uploading_completed t :uploaded_size 0)) :minithumbnail (:@type "minithumbnail" :width 8 :height 8 :data "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKy...") :has_animation nil :is_personal nil) :accent_color_id 6 :background_custom_emoji_id "0" :profile_accent_color_id -1 :profile_background_custom_emoji_id "0" :permissions (:@type "chatPermissions" :can_send_basic_messages nil :can_send_audios nil :can_send_documents nil :can_send_photos nil :can_send_videos nil :can_send_video_notes nil :can_send_voice_notes nil :can_send_polls nil :can_send_other_messages nil :can_add_web_page_previews nil :can_change_info nil :can_invite_users nil :can_pin_messages nil :can_create_topics nil) :positions [(:@type "chatPosition" :list (:@type "chatListMain") :order "7372930238306764723" :is_pinned nil)] :chat_lists [] :has_protected_content nil :is_translatable nil :is_marked_as_unread nil :view_as_topics nil :has_scheduled_messages nil :can_be_deleted_only_for_self nil :can_be_deleted_for_all_users nil :can_be_reported t :default_disable_notification nil :unread_count 75 :last_read_inbox_message_id 190966661120 :last_read_outbox_message_id 2251799812636672 :unread_mention_count 0 ...))
  telega-chats-dirty--update()
  telega-server--idle-timer-function()
  apply(telega-server--idle-timer-function nil)
  timer-event-handler([t 26193 59700 563047 nil telega-server--idle-timer-function nil nil 903000 nil])

**Comment by Frestein** [comment]
@zevlg  Has the bug returned? I’m getting this error again:
`Error running timer ‘telega-server--idle-timer-function’: (wrong-type-argument stringp nil)`

```
GNU Emacs 30.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.50, cairo version 1.18.4)
telega v0.8.452 (TDLib v1.8.51-bb474a2) (telega-server v0.8.3)
```
