### ISSUE TITLE
Notifications don't work without adding `telega-notifications-chat-message` to `telega-chat-post-message-hook`

### ISSUE THREAD

**Issue by flexibeast** [zevlg/telega.el#488]
*OS*: Gentoo
*Emacs*: 29.4
*Telega*: 0.8.291, installed from MELPA (as `telega-20240812.911`)

Enabling `telega-notifications-mode` alone isn't sufficient to enable notifications; i found i needed to add:

```
(add-hook 'telega-chat-post-message-hook 'telega-notifications-chat-message)
```
to my setup.

i can confirm that `telega-time-seconds` shows the correct time.

**Comment by zevlg** [comment]
Make sure you have enabled `telega-notifications-mode` with `(telega-notifications-mode 1)` in your setup

**Comment by flexibeast** [comment]
Oh, sorry, i'd misread the instructions as saying to `setq` `telega-notifications-mode` to `1`, rather than saying (as they actually do) to call the `telega-notifications-mode` function. My apologies for the noise; closing.
