### ISSUE TITLE
telega does not return to the original mode properly

### ISSUE THREAD

**Issue by harisonkhlil** [zevlg/telega.el#498]
## Telega Setup
*OS*:  Darwin JunFengs-MacBook-Pro.local 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:49:39 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6000 arm64
*Emacs*:  GNU Emacs 30.0.91 (build 1, aarch64-apple-darwin23.6.0, Ns appkit-2487.70 Version 14.7 (Build 23H124)) l
*Telega*:  telega vo.8.293

Setup with doom package!

## Current Behavior

Check out some of the information channels, chats, and channel threads when you're fishing `kill buffer` and it always comes back to the code workspace!

## Steps to Reproduce

1. open code workspace
2. open telega chat or channel talk and `kill-buffer`
3. Back to the code workspace instead of the `telega-root-mode` or `telega-chat-mode` that I wanted to go back to.

## Possible Solution

Channel post discussion after `kiil-buffer` should go back to the channel stream on the sand wall
After `telega-chat-mode` exits from `telega-root-mode`, it should go back to `root-mode`.

**Comment by zevlg** [comment]
This is beyond telega scope, and is up to you what to do when chatbuf is killed.

Use something like:
```
(defun my-telega-on-chatbuf-kill ()
  (when (eq major-mode 'telega-chat-mode)
    (telega)))

(add-hook 'kill-buffer-hook 'my-telega-on-chatbuf-kill)
```
To switch to rootbuf when some chatbuf is killed.
