### ISSUE TITLE
Failed to start server ./telega-server: error while loading shared libraries: libtdjson.so: cannot open shared object file: Error 40

### ISSUE THREAD

**Issue by cireu** [zevlg/telega.el#50]
Hello, I cloned your repo and tried to make the telega-server but I failed to start it with error message 

```
./telega-server: error while loading shared libraries: libtdjson.so: cannot open shared object file: Error 40
```
Here are some message maybe useful for you

```
chino@archlinux / % find / -name libtdjson.so 2>/dev/null
/usr/local/lib/libtdjson.so
/usr/lib/libtdjson.so
/home/chino/gitrepos/td/build/libtdjson.so
1 chino@archlinux / % echo $PATH                                                           :(
/home/chino/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/chino/.local/bin:/home/chino/.antigen/bundles/zsh-users/zsh-autosuggestions:/home/chino/.antigen/bundles/zdharma/fast-syntax-highlighting:/home/chino/.antigen/bundles/zsh-users/zsh-history-substring-search:/home/chino/.antigen/bundles/hlissner/zsh-autopair
chino@archlinux / % echo $LD_LIBRARY_PATH
/usr/lib64/nvidia/:/usr/lib32/nvidia:/usr/lib:
chino@archlinux / % ldd ~/.telega/telega-server 
	linux-vdso.so.1 (0x00007fff839f3000)
	libtdjson.so => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8b9bd0d000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8b9bb49000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8b9bd72000)
```

OS: Archlinux
Emacs Ver: 26.1
telega ver: Commit https://github.com/zevlg/telega.el/commit/e4d10f1f92233a7703aedf5e0841e5cc9a1001ea

**Comment by zevlg** [comment]
See https://github.com/zevlg/telega.el#faq

**Comment by cireu** [comment]
Oh! I'm really sorry for my careless. It works now, thanks to your reply

**Comment by agigao** [comment]
I had the same issue and spend quite a while searching the solution.
If Arch based distros are required to perform these actions, it might have a place in the documentation:

> Error `Libtdjson not found`

> Solution:
```console
# echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local_lib.conf
# ldconfig
```

The trick did the job.

Cheers,
Giga

**Comment by zevlg** [comment]
> I had the same issue and spend quite a while searching the solution.
> If Arch based distros are required to perform these actions, it might have a place in the documentation:
> 
> > Error `Libtdjson not found`
> 
> > Solution:
> 
> ```
> # echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local_lib.conf
> # ldconfig
> ```
> 
> The trick did the job.

Yeah, that is in FAQ
