### ISSUE TITLE
Disable output of special messages.

### ISSUE THREAD

**Issue by sarg** [zevlg/telega.el#51]
I'd like to have a `defcustom` that would allow me to disable display of `telega-msg-special-p` messages (user joined/leaved etc) in chat buffer.

**Comment by zevlg** [comment]
As to master branch there is already such functionality - message ignoring.  Take a look at `telega-msg-ignore-blocked-sender`.  It does not show messages from blocked users in common chats.

This functionality won't be enabled by default, because of 1.4 in https://core.telegram.org/api/terms
