### ISSUE TITLE
foundChatMessages error

### ISSUE THREAD

**Issue by OrionRandD** [zevlg/telega.el#510]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

telega v0.8.393 (TDLib v1.8.41-53acb2b) (telega-server v0.8.3)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

I am getting this error:

Debugger entered--Lisp error: (args-out-of-range [] 0)
  seq-elt([] 0)
  seq-first([])
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_85>((:@type "foundChatMessages" :total_count 0 :messages [] :next_from_message_id 0 :@extra 10))
  telega-server--dispatch-cmd("event" (:@type "foundChatMessages" :total_count 0 :messages [] :next_from_message_id 0 :@extra 10))
  apply(telega-server--dispatch-cmd ("event" (:@type "foundChatMessages" :total_count 0 :messages [] :next_from_message_id 0 :@extra 10)))
  telega-server--parse-commands()
  telega-server--filter(#<process telega-server> "event 62\n(:@type \"messageSenders\" :total_count 0 :...")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; when I start telega

;;  :(

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by zevlg** [comment]
Thanks for reporting this, should be fixed in the 0.8.394
