### ISSUE TITLE
Support Proxies

### ISSUE THREAD

**Issue by parhamdoustdar** [zevlg/telega.el#59]
Thanks a lot for this great package! I'm looking forward to using it!

I'm behind a corporate proxy, and right now, when I start `telega` for the first time and enter in my number, the screen only shows me that it's connecting.

I have the `http_proxy` and `https_proxy` and the capitalized counterparts set to the right value, and also have the `url-proxy-services` variable customized.

Thanks!

**Comment by zevlg** [comment]
`telega` supports proxies, see [FAQ](https://github.com/zevlg/telega.el#faq) and docstring for `telega-proxies` for more info

**Comment by parhamdoustdar** [comment]
Thanks, I had missed that. It works. :-)
