### ISSUE TITLE
Q: Can telega.el be used a custom VOIP telegram server? 

### ISSUE THREAD

**Issue by askucher** [zevlg/telega.el#63]
Just curious, is it possible to use this way: custom VOIP telegram server ?

**Comment by zevlg** [comment]
Hmm, what is custom VoIP telegram server?  VoIP in telegram is done in P2P manner, using telegram server just as connection point to exchange p2p info

**Comment by brettgilio** [comment]
@askucher Could you provide more information? I am going to close this issue due to inactivity until/unless we hear back. Thanks!
