### ISSUE TITLE
Make a new release? (desirable to contribute a Nix derivation)

### ISSUE THREAD

**Issue by vyorkin** [zevlg/telega.el#66]
Hey @zevlg! A couple of weeks ago we've discussed in telegram that it would be great to add the `telega-server` to [nixpkgs](https://github.com/NixOS/nixpkgs). I've already added the [tdlib derivation](https://github.com/NixOS/nixpkgs/pull/64685). It would be nice to make a new release so we can use the tagged version in a derivation. Here is my PR with details and related discussion: https://github.com/NixOS/nixpkgs/pull/64977#discussion_r304307531

**Comment by zevlg** [comment]
I've pushed "0.4.0" tag

**Comment by vyorkin** [comment]
Thank you!
