### ISSUE TITLE
lagging wen writing chat message in text-mode Emacs

### ISSUE THREAD

**Issue by mrkiko** [zevlg/telega.el#69]
When writing messages in text-mode Emacs, it seems something's blocking. Keypresses are echoed back after some time, with a relevant delay, which makes it difficult to contineu typing, for me at least. :)
I wasn't able to figure the UI enough to understand if it worked - since I am totally new to Emacs, and infact I installed it to try out telega.el :)
It will be very very nice for me it telega continues working even in text-mode Emacs.

**Comment by zevlg** [comment]
tty only mode is not yet supported by `telega.el`, will add this as feature

**Comment by zevlg** [comment]
@mrkiko please try latest master with `telega-use-images` set to nil.  Does it work for you?

**Comment by mrkiko** [comment]
THANKS A LOT!
I will try it out soon! Sorry for the late answer, wasn't at the PC those days....
Enrico

**Comment by mrkiko** [comment]
Hello!!
It works very very well!!!!!!!!
Thank you very very much man / all of you for this great development!!
