### ISSUE TITLE
Decrease default verbosity for telega-server

### ISSUE THREAD

**Issue by mrkiko** [zevlg/telega.el#70]
Maybe it would be better to set a lower default value for verbosity, maybe distinguishing a release and a dev build.
After minutes I had 2 megabytes of logging... But yes, I know this has pros and cons, consider it an opinion more than an "issue" report.

**Comment by zevlg** [comment]
During development it was very helpful to have this level of verbosity. Now when thing are settled down it is ok to decrease default level. Will do, thanks

**Comment by mrkiko** [comment]
Thank you!!
