### ISSUE TITLE
telega-server coredumps when redirecting log to /dev/null

### ISSUE THREAD

**Issue by mrkiko** [zevlg/telega.el#71]

**Comment by zevlg** [comment]
Could you please describe this in more details.  E.g. what you want to do, your configuration or what you are doing

**Comment by mrkiko** [comment]
Hello!
well - nothing special; I installed emacs-nox from Arch, librsvg or imagemagic not present - so I get the "processing filter" error.
I know nothing about emacs, so I googled around and found out I could do
M-x
customize

select [Applications],
select [Telega]
Select [Telegra-server]
Move to the relevant preference for logfile, pressing RET on "show value", editing value, applying and saving, exiting.
System is X86-64 with 16 GB RAM, 4.19.x kernel, Arch.
Than you very very much!

**Comment by zevlg** [comment]
"/dev/null" is not suitable value for `telega-server-logfile`, because TDLib handles logging, and it tries to rename it to /dev/null.old and gets permission denied.  I'll add workaround with `nil` value for `telega-server-logfile` to disable logging
