### ISSUE TITLE
Is imagemagick required for emacs27?

### ISSUE THREAD

**Issue by emacsomancer** [zevlg/telega.el#72]
Emacs 27 builds by default without imagemagick, using its own internal libraries to handle graphics. Can this be used by telega?

**Comment by cireu** [comment]
Can you point out what's new in image manipulation API of Emacs 27?

**Comment by emacsomancer** [comment]
@cireu 

From Emacs 27 NEWS:

> ** Emacs no longer defaults to using ImageMagick to display images,
due to security and stability concerns. 
.....
> +++
> ** Emacs now supports resizing and rotating images without ImageMagick.
All modern systems support this feature.  (On GNU and Unix systems,
Cairo drawing or the XRender extension to X11 is required for this to
be available; the configure script will test for it and, if found,
enable scaling.)

> The new function 'image-transforms-p' can be used to test whether any
given frame supports these capabilities.

(Searching in Emacs NEWS for 'imagemagick' provides a  few more details

**Comment by zevlg** [comment]
Imagemagick is no longer required.
