### ISSUE TITLE
Is there any way to make it work in Emacs-nox?

### ISSUE THREAD

**Issue by thoradically** [zevlg/telega.el#79]
I don't need pictures

**Comment by zevlg** [comment]
Not yet, this is to be done feature, see https://github.com/zevlg/telega.el/issues/69

**Comment by thoradically** [comment]
thanks! can't wait

**Comment by zevlg** [comment]
Please try latest master with `telega-use-images` set to `nil`

**Comment by thoradically** [comment]
@zevlg 

I added 
>(setq telega-use-images nil)
in my init.el

is that correct? if so nothing has changed, still getting the svg error

**Comment by zevlg** [comment]
Can you please be more verbose, which 'svg error' you are talking about?

svg.el is used even for emacs-nox, might also require librsvg support in emacs, can't check atm

**Comment by thoradically** [comment]
I get

>error in process filter: Invalid image type ‘svg’

when I enter a chat and the history won't load

also judging by [this](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/emacs-nox), emacs-nox in archlinux is built without svg support

**Comment by zevlg** [comment]
I see, I'll fix that
