### ISSUE TITLE
Suggestion: bind M-p to last message edditing

### ISSUE THREAD

**Issue by TatriX** [zevlg/telega.el#82]
Currently `M-p` is bound to `telega-chatbuf-input-prev` which essentially copies your previous message to the current input. It seems that replicating telegram-desktop behavior should be more usefull: use `M-p` to edit last sent message. I think it's the most common use-case when I want to do something with a previous message.

**Comment by zevlg** [comment]
Nice, suggestion!

Thanks

**Comment by zevlg** [comment]
Having this functionality `M-p C-M-c` will do what currently `M-p` do
