### ISSUE TITLE
Suggestion: only show modeline in the bottom-right window

### ISSUE THREAD

**Issue by TatriX** [zevlg/telega.el#83]
In Emacs one often has a lot of open windows. It seems that having status icons only in one, for instance bottom right window, makes more sense then showing it in every window's modeline.

I'm currently using simple trick to achieve this:
```elisp
  (telega-mode-line-mode 1)
  (setq global-mode-string (remove 'telega-mode-line-string global-mode-string))
  (add-to-list 'global-mode-string
               '(:eval (when (and (window-at-side-p nil 'bottom)
                                  (window-at-side-p nil 'right))
                         telega-mode-line-string)))
```

Please consider adding this feature by default ;)

**Comment by zevlg** [comment]
Or maybe display it in mode-line for selected window only?

**Comment by zevlg** [comment]
Or we should reorganize `telega-mode-line-mode` code a little bit, to make it fully customizable

**Comment by TatriX** [comment]
Well, yeah, it should be customizable. I prefer having things like tray/statusbar fixed.

**Comment by zevlg** [comment]
With last commit you can do:

```elisp
(setq telega-mode-line-format
      (list '(:eval (when (and (window-at-side-p nil 'bottom)
                               (window-at-side-p nil 'right)
                               (telega-server-live-p))
                      telega-mode-line-string))))
```

to achieve behaviour you need
