### ISSUE TITLE
Cannot forward messages with non-English input method

### ISSUE THREAD

**Issue by TatriX** [zevlg/telega.el#85]
When Emacs input-method is in use (via `(setq default-input-method 'russian-computer)` and `(toggle-input-method) ` for example), and when one wants to forward message by pressing `f` on the message, it doesn't work.

In English layout `f` is bound to `(telega-msg-forward MSG CHAT)`
while in Russian:
```
а (translated from f а) runs the command ignore (found in
telega-msg-button-map), which is an interactive compiled Lisp function
in ‘subr.el’.

It is bound to many ordinary text characters.

(ignore &rest IGNORE)
```

**Comment by zevlg** [comment]
Ah, is there some code sample how to bind keys in input-method aware way?

**Comment by TatriX** [comment]
No idea tbh. Most of the bindings use modifier keys and they work with any input method.

**Comment by zevlg** [comment]
Need some investigation, `dired-mode`'s single key bindings works well with different input-method

**Comment by zevlg** [comment]
Fixed in master Emacs, see https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00093.html

**Comment by TatriX** [comment]
Works like a charm, thanks!
