### ISSUE TITLE
error in process filter: Window system frame should be used

### ISSUE THREAD

**Issue by mrkiko** [zevlg/telega.el#86]
emacs says that when I try to write to our groupchat from within emacs in text mode.

**Comment by mrkiko** [comment]
Should add that now my emacs has both RSVG and imagemagick support, and that in the end I switched to the standard "emacs" ARCH package, switching from the -nox one.
Still I am in text mode.
Thank you for your GREAT work!

**Comment by zevlg** [comment]
set `telega-use-images` to nil

> emacs says that when I try to write to our groupchat from within emacs in text mode.

**Comment by mrkiko** [comment]
OOPS - sorry! you told me this at least twice and I didn't do that.
Sorry for the noise!!
