### ISSUE TITLE
Telega workflow

### ISSUE THREAD

**Issue by TatriX** [zevlg/telega.el#87]
I assume that author is using telega on daily basis. Could you please describe your workflow?
For example:  
- how do you switch between chats and root window
- you've got a new message, how do you switch to it?
- you want to attach an image, how do you preview what are you attaching?
- do you use something like `display-buffer-alist` to mimic desktop client, i.e. always show a root window in a specified place

**Comment by zevlg** [comment]
> I assume that author is using telega on daily basis. Could you please describe your workflow?
> For example:
> 
> * how do you switch between chats and root window

To switch to root buffer I have <kbd>C-c t</kbd> -> `telega`, to switch between chat buffers, I just use ordinary Emacs buffer switching commands.  I also have <kbd>C-c C-t</kbd> to switch to "SavedMessages" chatbuffer.

> * you've got a new message, how do you switch to it?

It depends on what kind of message I see (I see telega state in modeline), if it is urgent message, that requires ASAP reply, I just switch to this chat using some custom commands or by just clicking on corresponding modeline  label, telega will show root buffer with some filter applied.

If it is the message in opened chat, I use tracking and cycle such just using ordinary <kbd>C-c SPC</kbd>

> * you want to attach an image, how do you preview what are you attaching?

I just open the image file in Emacs and use a command to send file to chat as photo.  This command will be built-in telega soon, see below

> * do you use something like `display-buffer-alist` to mimic desktop client, i.e. always show a root window in a specified place

No, but there is `telega-chat--display-buffer-action` to take action on chat buffer display.  I almost always use single-window Emacs setup, splitting vertically sometimes to get some help, such as `M-x apropos RET` or compilation output, so I don't need some complex setup for `display-buffer-alist`


In general, if you don't know what to do, but you think that some chat requires your attention, you can just run `M-x telega RET` and take actions according to what you see in root buffer.

I'm planning to add `telega-prefix-map` to be bound to <kbd>C-t t</kbd> to perform some frequent telega commands, such as:
* <kbd>C-c t t</kbd> -> `telega`  (switches to root buffer if telega is running)
* <kbd>C-c t t</kbd> -> `telega-saved-messages`
* <kbd>C-c t f</kbd> -> `telega-file-send`
* <kbd>C-c t w</kbd> -> `telega-file-write` (write file in chat's collaborative editing)
* <kbd>C-c t b</kbd> -> `telega-switch-chat`  (like <kbd>C-x b</kbd>, but for chat buffers only)
etc

**Comment by TatriX** [comment]
I see.
Currently I uses setup based on `display-buffer-alist`:
```elisp
(setq display-buffer-alist
      `(("\\*Telega Root\\*" display-buffer-in-side-window
         (side . left)
         (slot . 0)
         (window-width . 80)
         (window-height . fit-window-to-buffer)
         (window-parameters . ((no-delete-other-windows . t))))))
```
And then 
```elisp
:bind (:map telega-chat-mode-map ("C-c C-z" . (lambda ()
                                                  (interactive)
                                                  (switch-to-buffer-other-window "*Telega Root*"))))
```
So I have pinned root window on the left side on a static exwm workspace, and I can quickly go back to root window from any chat window.
It would be nice if root window could be rendered the same way as in desktop client, i.e. with one column for both nicknames as well as status/last messages.

**Comment by zevlg** [comment]
JFYI: it is better to use `telega-root-buffer-name` instead of direct "*Telega Root*"

**Comment by zevlg** [comment]
With last commit you might use code like this:
```elisp
(defun my-ins--chat-2lines (chat)
  (telega-ins--chat chat)
  (telega-ins "\n")
  (telega-ins--with-props
      '(face default display ((line-height 0.5) (height 0.5)))
    (telega-ins "  ")
    (telega-ins--chat-status chat (+ 3 (* 2 telega-chat-button-width)))
    (telega-ins "\n"))
  t)

(setq telega-filter-button-width 30)
(setq telega-filters-custom
      (list (cons "Unread/Unmuted" '(and unread unmuted))
            (cons "Mentions" '(mention))))
(setq telega-root-fill-column 32)
(setq telega-inserter-for-chat-button 'my-ins--chat-2lines)
```

*before* loading telega.el
