### ISSUE TITLE
Support for custom fonts

### ISSUE THREAD

**Issue by toure00** [zevlg/telega.el#90]
Hello, I am a foreign language user, most fonts are not Monospaced in my native font.
![image](https://user-images.githubusercontent.com/33457469/65172621-e6d60c00-da7f-11e9-8f23-f5b8a8374323.png)

I need to set the font separately to align the content.
```lisp
(use-package telega
  :commands (telega)
  :defer t
  :init
  (global-set-key (kbd "C-c t") 'telega)
  ;;set proxy
  (setq telega-proxies (list '(:server "127.0.0.1" :port 1080 :enable t :type (:@type "proxyTypeSocks5"))))
  ;; set font
  (defun telega-buffer-face-mode-variable ()
    (interactive)
    (make-face 'my-telega-face)
    ;; (set-face-attribute 'my-telega-face nil :font "M+ 1m")
    (set-face-attribute 'my-telega-face nil :font "等距更纱黑体 SC 13")
    (setq buffer-face-mode-face 'my-telega-face)
    (buffer-face-mode))
  (add-hook 'telega-root-mode-hook 'telega-buffer-face-mode-variable)
  (add-hook 'telega-webpage-mode-hook 'telega-buffer-face-mode-variable)
  (add-hook 'telega-chat-mode-hook 'telega-buffer-face-mode-variable))
```
But after I set the font, the image display a gap.
![image](https://user-images.githubusercontent.com/33457469/65172543-b9895e00-da7f-11e9-91ff-9e3ffc46c6e3.png)

Can you provide a way to customize the font?
Many thanks!

**Comment by zevlg** [comment]
@toure00 could you please check, does this commit actually fixes things for you?  Reopen if not

**Comment by toure00** [comment]
Unfortunately, this does not take effect.

**Comment by zevlg** [comment]
> Unfortunately, this does not take effect.

What is your Emacs version? Having chat buffer current with buffer-face-mode active, please eval:
 1) (telega-chars-xheight 1)
 2) (frame-char-height)

**Comment by toure00** [comment]
Emacse version: 26.2
(telega-chars-xheight 1) ;; 15
(frame-char-height)      ;; 15

**Comment by toure00** [comment]
macOS 10.14.3
Emacs-plus
run emacs -Q
![image](https://user-images.githubusercontent.com/33457469/65375453-a61d0380-dcc8-11e9-9a0c-110c551445d1.png)
Enlarging the font will cause problems.
I hope this information is useful to you.

**Comment by zevlg** [comment]
> 1. (telega-chars-xheight 1)
> 2. (frame-char-height)

 And those calls still report same size?  Are you sure you updated the master?

I’ll check, thanks

**Comment by toure00** [comment]
Sorry, my elpa source update is slow, the 20th update is still the old version, after the update today, everything is normal, thank you

**Comment by zevlg** [comment]
@toure00 could you please check, does last commit fixes things for you?

**Comment by toure00** [comment]
Yes, display properly
