### ISSUE TITLE
Custom lable not support emoji

### ISSUE THREAD

**Issue by toure00** [zevlg/telega.el#94]
Custom label not support emoji
Should display 💬 in  Custom label

![image](https://user-images.githubusercontent.com/33457469/67030848-dda19300-f142-11e9-9304-eba7984e92c1.png)

**Comment by zevlg** [comment]
Use direct unicode symbol instead, not surrogated pair

**Comment by zevlg** [comment]
Ah, you’ve used direct unicode symbol initially and it displays as surrogated pair?

**Comment by toure00** [comment]
Look this

![1](https://user-images.githubusercontent.com/33457469/67067936-d4e4a780-f1aa-11e9-8b81-0cbf49ed28a1.gif)

**Comment by zevlg** [comment]
@toure00 can you confirm the issue is fixed?

**Comment by toure00** [comment]
Yes, this issue is fixed
