### ISSUE TITLE
Improve "forward" usability

### ISSUE THREAD

**Issue by TatriX** [zevlg/telega.el#96]
Let's say you have 2 windows open, one for Alice and one for Bob.
Now you want to forward a message from Alice to Bob. You select window with Alice, pick a message, press `f` and select a recipient. After you hit `RET` Bob's window will replace current one, so you now have 2 open windows both for Bob. I believe it could be useful by default to use something like `display-buffer-reuse-window`. Thanks!

**Comment by zevlg** [comment]
There is already `telega-chat--display-buffer-action` to control how chat buffer pops up.  You could set it to `'(display-buffer-reuse-window)` value to get behaviour you want

**Comment by TatriX** [comment]
Thanks, that helps!
