### ISSUE TITLE
Imagemagick support will be disabled by default in emacs 27

### ISSUE THREAD

**Issue by Ergus** [zevlg/telega.el#97]
Hi:

In the next emacs 27 release imagemagic support will be disabled by default. We are trying to remove the Imagemagick in favor of the new png and img API as it is better for security, functionality and performance.

It is reported in the NEWS as:

* Emacs no longer defaults to using ImageMagick to display images, due to security and stability concerns.

**Comment by zevlg** [comment]
Dup https://github.com/zevlg/telega.el/issues/72

**Comment by Ergus** [comment]
OK, I'll close it then.
